//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IqSoft.CP.Integration.SDPayCustomer {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://payout.sdapay.net/", ConfigurationName="SDPayCustomer.CustomerSoap")]
    public interface CustomerSoap {
        
        // CODEGEN: Generating message contract since the wrapper namespace (http://payout.sdapay.net/ApplyForABank.asmx/T) of message GetFundRequest does not match the default value (http://payout.sdapay.net/)
        [System.ServiceModel.OperationContractAttribute(Action="http://payout.sdapay.net/ApplyForABank.asmx/GetFund", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        IqSoft.CP.Integration.SDPayCustomer.GetFundResponse GetFund(IqSoft.CP.Integration.SDPayCustomer.GetFundRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://payout.sdapay.net/ApplyForABank.asmx/GetFund", ReplyAction="*")]
        System.Threading.Tasks.Task<IqSoft.CP.Integration.SDPayCustomer.GetFundResponse> GetFundAsync(IqSoft.CP.Integration.SDPayCustomer.GetFundRequest request);
        
        // CODEGEN: Generating message contract since the wrapper namespace (http://payout.sdapay.net/ApplyForABank.asmx/T) of message GetFundMacRequest does not match the default value (http://payout.sdapay.net/)
        [System.ServiceModel.OperationContractAttribute(Action="http://payout.sdapay.net/ApplyForABank.asmx/GetFundMac", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        IqSoft.CP.Integration.SDPayCustomer.GetFundMacResponse GetFundMac(IqSoft.CP.Integration.SDPayCustomer.GetFundMacRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://payout.sdapay.net/ApplyForABank.asmx/GetFundMac", ReplyAction="*")]
        System.Threading.Tasks.Task<IqSoft.CP.Integration.SDPayCustomer.GetFundMacResponse> GetFundMacAsync(IqSoft.CP.Integration.SDPayCustomer.GetFundMacRequest request);
        
        // CODEGEN: Generating message contract since the wrapper namespace (http://payout.sdapay.net/ApplyForABank.asmx/T) of message ExitTransferInfomationModelRequest does not match the default value (http://payout.sdapay.net/)
        [System.ServiceModel.OperationContractAttribute(Action="http://payout.sdapay.net/ApplyForABank.asmx/ExitTransferInfomationModelSerialNumb" +
            "er", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        IqSoft.CP.Integration.SDPayCustomer.ExitTransferInfomationModelResponse ExitTransferInfomationModel(IqSoft.CP.Integration.SDPayCustomer.ExitTransferInfomationModelRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://payout.sdapay.net/ApplyForABank.asmx/ExitTransferInfomationModelSerialNumb" +
            "er", ReplyAction="*")]
        System.Threading.Tasks.Task<IqSoft.CP.Integration.SDPayCustomer.ExitTransferInfomationModelResponse> ExitTransferInfomationModelAsync(IqSoft.CP.Integration.SDPayCustomer.ExitTransferInfomationModelRequest request);
        
        // CODEGEN: Generating message contract since the wrapper namespace (http://payout.sdapay.net/ApplyForABank.asmx/T) of message ExitTransferInfomationModelSerialNumberRequest does not match the default value (http://payout.sdapay.net/)
        [System.ServiceModel.OperationContractAttribute(Action="http://payout.sdapay.net/ApplyForABank.asmx/ExitTransferInfomationModel", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        IqSoft.CP.Integration.SDPayCustomer.ExitTransferInfomationModelSerialNumberResponse ExitTransferInfomationModelSerialNumber(IqSoft.CP.Integration.SDPayCustomer.ExitTransferInfomationModelSerialNumberRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://payout.sdapay.net/ApplyForABank.asmx/ExitTransferInfomationModel", ReplyAction="*")]
        System.Threading.Tasks.Task<IqSoft.CP.Integration.SDPayCustomer.ExitTransferInfomationModelSerialNumberResponse> ExitTransferInfomationModelSerialNumberAsync(IqSoft.CP.Integration.SDPayCustomer.ExitTransferInfomationModelSerialNumberRequest request);
        
        // CODEGEN: Generating message contract since the wrapper namespace (http://payout.sdapay.net/ApplyForABank.asmx/T) of message ExitTransferInfomationModelMacRequest does not match the default value (http://payout.sdapay.net/)
        [System.ServiceModel.OperationContractAttribute(Action="http://payout.sdapay.net/ApplyForABank.asmx/ExitTransferInfomationModelMac", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        IqSoft.CP.Integration.SDPayCustomer.ExitTransferInfomationModelMacResponse ExitTransferInfomationModelMac(IqSoft.CP.Integration.SDPayCustomer.ExitTransferInfomationModelMacRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://payout.sdapay.net/ApplyForABank.asmx/ExitTransferInfomationModelMac", ReplyAction="*")]
        System.Threading.Tasks.Task<IqSoft.CP.Integration.SDPayCustomer.ExitTransferInfomationModelMacResponse> ExitTransferInfomationModelMacAsync(IqSoft.CP.Integration.SDPayCustomer.ExitTransferInfomationModelMacRequest request);
        
        // CODEGEN: Generating message contract since the wrapper namespace (http://payout.sdapay.net/ApplyForABank.asmx/T) of message ExitTransferInfomationModelSerialNumberMacRequest does not match the default value (http://payout.sdapay.net/)
        [System.ServiceModel.OperationContractAttribute(Action="http://payout.sdapay.net/ApplyForABank.asmx/ExitTransferInfomationModelSerialNumb" +
            "erMac", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        IqSoft.CP.Integration.SDPayCustomer.ExitTransferInfomationModelSerialNumberMacResponse ExitTransferInfomationModelSerialNumberMac(IqSoft.CP.Integration.SDPayCustomer.ExitTransferInfomationModelSerialNumberMacRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://payout.sdapay.net/ApplyForABank.asmx/ExitTransferInfomationModelSerialNumb" +
            "erMac", ReplyAction="*")]
        System.Threading.Tasks.Task<IqSoft.CP.Integration.SDPayCustomer.ExitTransferInfomationModelSerialNumberMacResponse> ExitTransferInfomationModelSerialNumberMacAsync(IqSoft.CP.Integration.SDPayCustomer.ExitTransferInfomationModelSerialNumberMacRequest request);
        
        // CODEGEN: Generating message contract since the wrapper namespace (http://payout.sdapay.net/ApplyForABank.asmx/T) of message GetBalancesRequest does not match the default value (http://payout.sdapay.net/)
        [System.ServiceModel.OperationContractAttribute(Action="http://payout.sdapay.net/ApplyForABank.asmx/GetBalances", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        IqSoft.CP.Integration.SDPayCustomer.GetBalancesResponse GetBalances(IqSoft.CP.Integration.SDPayCustomer.GetBalancesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://payout.sdapay.net/ApplyForABank.asmx/GetBalances", ReplyAction="*")]
        System.Threading.Tasks.Task<IqSoft.CP.Integration.SDPayCustomer.GetBalancesResponse> GetBalancesAsync(IqSoft.CP.Integration.SDPayCustomer.GetBalancesRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetFund", WrapperNamespace="http://payout.sdapay.net/ApplyForABank.asmx/T", IsWrapped=true)]
    public partial class GetFundRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string LoginAccount;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string GetFundInfo;
        
        public GetFundRequest() {
        }
        
        public GetFundRequest(string LoginAccount, string GetFundInfo) {
            this.LoginAccount = LoginAccount;
            this.GetFundInfo = GetFundInfo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetFundResponse", WrapperNamespace="http://payout.sdapay.net/ApplyForABank.asmx/T", IsWrapped=true)]
    public partial class GetFundResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public int GetFundResult;
        
        public GetFundResponse() {
        }
        
        public GetFundResponse(int GetFundResult) {
            this.GetFundResult = GetFundResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetFundMac", WrapperNamespace="http://payout.sdapay.net/ApplyForABank.asmx/T", IsWrapped=true)]
    public partial class GetFundMacRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string LoginAccount;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string GetFundInfo;
        
        public GetFundMacRequest() {
        }
        
        public GetFundMacRequest(string LoginAccount, string GetFundInfo) {
            this.LoginAccount = LoginAccount;
            this.GetFundInfo = GetFundInfo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetFundMacResponse", WrapperNamespace="http://payout.sdapay.net/ApplyForABank.asmx/T", IsWrapped=true)]
    public partial class GetFundMacResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public int GetFundMacResult;
        
        public GetFundMacResponse() {
        }
        
        public GetFundMacResponse(int GetFundMacResult) {
            this.GetFundMacResult = GetFundMacResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ExitTransferInfomationModel", WrapperNamespace="http://payout.sdapay.net/ApplyForABank.asmx/T", IsWrapped=true)]
    public partial class ExitTransferInfomationModelRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string LoginAccount;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public int Id;
        
        public ExitTransferInfomationModelRequest() {
        }
        
        public ExitTransferInfomationModelRequest(string LoginAccount, int Id) {
            this.LoginAccount = LoginAccount;
            this.Id = Id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ExitTransferInfomationModelResponse", WrapperNamespace="http://payout.sdapay.net/ApplyForABank.asmx/T", IsWrapped=true)]
    public partial class ExitTransferInfomationModelResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string ExitTransferInfomationModelResult;
        
        public ExitTransferInfomationModelResponse() {
        }
        
        public ExitTransferInfomationModelResponse(string ExitTransferInfomationModelResult) {
            this.ExitTransferInfomationModelResult = ExitTransferInfomationModelResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ExitTransferInfomationModelSerialNumber", WrapperNamespace="http://payout.sdapay.net/ApplyForABank.asmx/T", IsWrapped=true)]
    public partial class ExitTransferInfomationModelSerialNumberRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string LoginAccount;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string SerialNumber;
        
        public ExitTransferInfomationModelSerialNumberRequest() {
        }
        
        public ExitTransferInfomationModelSerialNumberRequest(string LoginAccount, string SerialNumber) {
            this.LoginAccount = LoginAccount;
            this.SerialNumber = SerialNumber;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ExitTransferInfomationModelSerialNumberResponse", WrapperNamespace="http://payout.sdapay.net/ApplyForABank.asmx/T", IsWrapped=true)]
    public partial class ExitTransferInfomationModelSerialNumberResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string ExitTransferInfomationModelSerialNumberResult;
        
        public ExitTransferInfomationModelSerialNumberResponse() {
        }
        
        public ExitTransferInfomationModelSerialNumberResponse(string ExitTransferInfomationModelSerialNumberResult) {
            this.ExitTransferInfomationModelSerialNumberResult = ExitTransferInfomationModelSerialNumberResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ExitTransferInfomationModelMac", WrapperNamespace="http://payout.sdapay.net/ApplyForABank.asmx/T", IsWrapped=true)]
    public partial class ExitTransferInfomationModelMacRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string LoginAccount;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public int Id;
        
        public ExitTransferInfomationModelMacRequest() {
        }
        
        public ExitTransferInfomationModelMacRequest(string LoginAccount, int Id) {
            this.LoginAccount = LoginAccount;
            this.Id = Id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ExitTransferInfomationModelMacResponse", WrapperNamespace="http://payout.sdapay.net/ApplyForABank.asmx/T", IsWrapped=true)]
    public partial class ExitTransferInfomationModelMacResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string ExitTransferInfomationModelMacResult;
        
        public ExitTransferInfomationModelMacResponse() {
        }
        
        public ExitTransferInfomationModelMacResponse(string ExitTransferInfomationModelMacResult) {
            this.ExitTransferInfomationModelMacResult = ExitTransferInfomationModelMacResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ExitTransferInfomationModelSerialNumberMac", WrapperNamespace="http://payout.sdapay.net/ApplyForABank.asmx/T", IsWrapped=true)]
    public partial class ExitTransferInfomationModelSerialNumberMacRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string LoginAccount;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string SerialNumber;
        
        public ExitTransferInfomationModelSerialNumberMacRequest() {
        }
        
        public ExitTransferInfomationModelSerialNumberMacRequest(string LoginAccount, string SerialNumber) {
            this.LoginAccount = LoginAccount;
            this.SerialNumber = SerialNumber;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ExitTransferInfomationModelSerialNumberMacResponse", WrapperNamespace="http://payout.sdapay.net/ApplyForABank.asmx/T", IsWrapped=true)]
    public partial class ExitTransferInfomationModelSerialNumberMacResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string ExitTransferInfomationModelSerialNumberMacResult;
        
        public ExitTransferInfomationModelSerialNumberMacResponse() {
        }
        
        public ExitTransferInfomationModelSerialNumberMacResponse(string ExitTransferInfomationModelSerialNumberMacResult) {
            this.ExitTransferInfomationModelSerialNumberMacResult = ExitTransferInfomationModelSerialNumberMacResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetBalances", WrapperNamespace="http://payout.sdapay.net/ApplyForABank.asmx/T", IsWrapped=true)]
    public partial class GetBalancesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string CardNum;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string LoginName;
        
        public GetBalancesRequest() {
        }
        
        public GetBalancesRequest(string CardNum, string LoginName) {
            this.CardNum = CardNum;
            this.LoginName = LoginName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetBalancesResponse", WrapperNamespace="http://payout.sdapay.net/ApplyForABank.asmx/T", IsWrapped=true)]
    public partial class GetBalancesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string GetBalancesResult;
        
        public GetBalancesResponse() {
        }
        
        public GetBalancesResponse(string GetBalancesResult) {
            this.GetBalancesResult = GetBalancesResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface CustomerSoapChannel : IqSoft.CP.Integration.SDPayCustomer.CustomerSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CustomerSoapClient : System.ServiceModel.ClientBase<IqSoft.CP.Integration.SDPayCustomer.CustomerSoap>, IqSoft.CP.Integration.SDPayCustomer.CustomerSoap {
        
        public CustomerSoapClient() {
        }
        
        public CustomerSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CustomerSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CustomerSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CustomerSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        IqSoft.CP.Integration.SDPayCustomer.GetFundResponse IqSoft.CP.Integration.SDPayCustomer.CustomerSoap.GetFund(IqSoft.CP.Integration.SDPayCustomer.GetFundRequest request) {
            return base.Channel.GetFund(request);
        }
        
        public int GetFund(string LoginAccount, string GetFundInfo) {
            IqSoft.CP.Integration.SDPayCustomer.GetFundRequest inValue = new IqSoft.CP.Integration.SDPayCustomer.GetFundRequest();
            inValue.LoginAccount = LoginAccount;
            inValue.GetFundInfo = GetFundInfo;
            IqSoft.CP.Integration.SDPayCustomer.GetFundResponse retVal = ((IqSoft.CP.Integration.SDPayCustomer.CustomerSoap)(this)).GetFund(inValue);
            return retVal.GetFundResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<IqSoft.CP.Integration.SDPayCustomer.GetFundResponse> IqSoft.CP.Integration.SDPayCustomer.CustomerSoap.GetFundAsync(IqSoft.CP.Integration.SDPayCustomer.GetFundRequest request) {
            return base.Channel.GetFundAsync(request);
        }
        
        public System.Threading.Tasks.Task<IqSoft.CP.Integration.SDPayCustomer.GetFundResponse> GetFundAsync(string LoginAccount, string GetFundInfo) {
            IqSoft.CP.Integration.SDPayCustomer.GetFundRequest inValue = new IqSoft.CP.Integration.SDPayCustomer.GetFundRequest();
            inValue.LoginAccount = LoginAccount;
            inValue.GetFundInfo = GetFundInfo;
            return ((IqSoft.CP.Integration.SDPayCustomer.CustomerSoap)(this)).GetFundAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        IqSoft.CP.Integration.SDPayCustomer.GetFundMacResponse IqSoft.CP.Integration.SDPayCustomer.CustomerSoap.GetFundMac(IqSoft.CP.Integration.SDPayCustomer.GetFundMacRequest request) {
            return base.Channel.GetFundMac(request);
        }
        
        public int GetFundMac(string LoginAccount, string GetFundInfo) {
            IqSoft.CP.Integration.SDPayCustomer.GetFundMacRequest inValue = new IqSoft.CP.Integration.SDPayCustomer.GetFundMacRequest();
            inValue.LoginAccount = LoginAccount;
            inValue.GetFundInfo = GetFundInfo;
            IqSoft.CP.Integration.SDPayCustomer.GetFundMacResponse retVal = ((IqSoft.CP.Integration.SDPayCustomer.CustomerSoap)(this)).GetFundMac(inValue);
            return retVal.GetFundMacResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<IqSoft.CP.Integration.SDPayCustomer.GetFundMacResponse> IqSoft.CP.Integration.SDPayCustomer.CustomerSoap.GetFundMacAsync(IqSoft.CP.Integration.SDPayCustomer.GetFundMacRequest request) {
            return base.Channel.GetFundMacAsync(request);
        }
        
        public System.Threading.Tasks.Task<IqSoft.CP.Integration.SDPayCustomer.GetFundMacResponse> GetFundMacAsync(string LoginAccount, string GetFundInfo) {
            IqSoft.CP.Integration.SDPayCustomer.GetFundMacRequest inValue = new IqSoft.CP.Integration.SDPayCustomer.GetFundMacRequest();
            inValue.LoginAccount = LoginAccount;
            inValue.GetFundInfo = GetFundInfo;
            return ((IqSoft.CP.Integration.SDPayCustomer.CustomerSoap)(this)).GetFundMacAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        IqSoft.CP.Integration.SDPayCustomer.ExitTransferInfomationModelResponse IqSoft.CP.Integration.SDPayCustomer.CustomerSoap.ExitTransferInfomationModel(IqSoft.CP.Integration.SDPayCustomer.ExitTransferInfomationModelRequest request) {
            return base.Channel.ExitTransferInfomationModel(request);
        }
        
        public string ExitTransferInfomationModel(string LoginAccount, int Id) {
            IqSoft.CP.Integration.SDPayCustomer.ExitTransferInfomationModelRequest inValue = new IqSoft.CP.Integration.SDPayCustomer.ExitTransferInfomationModelRequest();
            inValue.LoginAccount = LoginAccount;
            inValue.Id = Id;
            IqSoft.CP.Integration.SDPayCustomer.ExitTransferInfomationModelResponse retVal = ((IqSoft.CP.Integration.SDPayCustomer.CustomerSoap)(this)).ExitTransferInfomationModel(inValue);
            return retVal.ExitTransferInfomationModelResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<IqSoft.CP.Integration.SDPayCustomer.ExitTransferInfomationModelResponse> IqSoft.CP.Integration.SDPayCustomer.CustomerSoap.ExitTransferInfomationModelAsync(IqSoft.CP.Integration.SDPayCustomer.ExitTransferInfomationModelRequest request) {
            return base.Channel.ExitTransferInfomationModelAsync(request);
        }
        
        public System.Threading.Tasks.Task<IqSoft.CP.Integration.SDPayCustomer.ExitTransferInfomationModelResponse> ExitTransferInfomationModelAsync(string LoginAccount, int Id) {
            IqSoft.CP.Integration.SDPayCustomer.ExitTransferInfomationModelRequest inValue = new IqSoft.CP.Integration.SDPayCustomer.ExitTransferInfomationModelRequest();
            inValue.LoginAccount = LoginAccount;
            inValue.Id = Id;
            return ((IqSoft.CP.Integration.SDPayCustomer.CustomerSoap)(this)).ExitTransferInfomationModelAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        IqSoft.CP.Integration.SDPayCustomer.ExitTransferInfomationModelSerialNumberResponse IqSoft.CP.Integration.SDPayCustomer.CustomerSoap.ExitTransferInfomationModelSerialNumber(IqSoft.CP.Integration.SDPayCustomer.ExitTransferInfomationModelSerialNumberRequest request) {
            return base.Channel.ExitTransferInfomationModelSerialNumber(request);
        }
        
        public string ExitTransferInfomationModelSerialNumber(string LoginAccount, string SerialNumber) {
            IqSoft.CP.Integration.SDPayCustomer.ExitTransferInfomationModelSerialNumberRequest inValue = new IqSoft.CP.Integration.SDPayCustomer.ExitTransferInfomationModelSerialNumberRequest();
            inValue.LoginAccount = LoginAccount;
            inValue.SerialNumber = SerialNumber;
            IqSoft.CP.Integration.SDPayCustomer.ExitTransferInfomationModelSerialNumberResponse retVal = ((IqSoft.CP.Integration.SDPayCustomer.CustomerSoap)(this)).ExitTransferInfomationModelSerialNumber(inValue);
            return retVal.ExitTransferInfomationModelSerialNumberResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<IqSoft.CP.Integration.SDPayCustomer.ExitTransferInfomationModelSerialNumberResponse> IqSoft.CP.Integration.SDPayCustomer.CustomerSoap.ExitTransferInfomationModelSerialNumberAsync(IqSoft.CP.Integration.SDPayCustomer.ExitTransferInfomationModelSerialNumberRequest request) {
            return base.Channel.ExitTransferInfomationModelSerialNumberAsync(request);
        }
        
        public System.Threading.Tasks.Task<IqSoft.CP.Integration.SDPayCustomer.ExitTransferInfomationModelSerialNumberResponse> ExitTransferInfomationModelSerialNumberAsync(string LoginAccount, string SerialNumber) {
            IqSoft.CP.Integration.SDPayCustomer.ExitTransferInfomationModelSerialNumberRequest inValue = new IqSoft.CP.Integration.SDPayCustomer.ExitTransferInfomationModelSerialNumberRequest();
            inValue.LoginAccount = LoginAccount;
            inValue.SerialNumber = SerialNumber;
            return ((IqSoft.CP.Integration.SDPayCustomer.CustomerSoap)(this)).ExitTransferInfomationModelSerialNumberAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        IqSoft.CP.Integration.SDPayCustomer.ExitTransferInfomationModelMacResponse IqSoft.CP.Integration.SDPayCustomer.CustomerSoap.ExitTransferInfomationModelMac(IqSoft.CP.Integration.SDPayCustomer.ExitTransferInfomationModelMacRequest request) {
            return base.Channel.ExitTransferInfomationModelMac(request);
        }
        
        public string ExitTransferInfomationModelMac(string LoginAccount, int Id) {
            IqSoft.CP.Integration.SDPayCustomer.ExitTransferInfomationModelMacRequest inValue = new IqSoft.CP.Integration.SDPayCustomer.ExitTransferInfomationModelMacRequest();
            inValue.LoginAccount = LoginAccount;
            inValue.Id = Id;
            IqSoft.CP.Integration.SDPayCustomer.ExitTransferInfomationModelMacResponse retVal = ((IqSoft.CP.Integration.SDPayCustomer.CustomerSoap)(this)).ExitTransferInfomationModelMac(inValue);
            return retVal.ExitTransferInfomationModelMacResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<IqSoft.CP.Integration.SDPayCustomer.ExitTransferInfomationModelMacResponse> IqSoft.CP.Integration.SDPayCustomer.CustomerSoap.ExitTransferInfomationModelMacAsync(IqSoft.CP.Integration.SDPayCustomer.ExitTransferInfomationModelMacRequest request) {
            return base.Channel.ExitTransferInfomationModelMacAsync(request);
        }
        
        public System.Threading.Tasks.Task<IqSoft.CP.Integration.SDPayCustomer.ExitTransferInfomationModelMacResponse> ExitTransferInfomationModelMacAsync(string LoginAccount, int Id) {
            IqSoft.CP.Integration.SDPayCustomer.ExitTransferInfomationModelMacRequest inValue = new IqSoft.CP.Integration.SDPayCustomer.ExitTransferInfomationModelMacRequest();
            inValue.LoginAccount = LoginAccount;
            inValue.Id = Id;
            return ((IqSoft.CP.Integration.SDPayCustomer.CustomerSoap)(this)).ExitTransferInfomationModelMacAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        IqSoft.CP.Integration.SDPayCustomer.ExitTransferInfomationModelSerialNumberMacResponse IqSoft.CP.Integration.SDPayCustomer.CustomerSoap.ExitTransferInfomationModelSerialNumberMac(IqSoft.CP.Integration.SDPayCustomer.ExitTransferInfomationModelSerialNumberMacRequest request) {
            return base.Channel.ExitTransferInfomationModelSerialNumberMac(request);
        }
        
        public string ExitTransferInfomationModelSerialNumberMac(string LoginAccount, string SerialNumber) {
            IqSoft.CP.Integration.SDPayCustomer.ExitTransferInfomationModelSerialNumberMacRequest inValue = new IqSoft.CP.Integration.SDPayCustomer.ExitTransferInfomationModelSerialNumberMacRequest();
            inValue.LoginAccount = LoginAccount;
            inValue.SerialNumber = SerialNumber;
            IqSoft.CP.Integration.SDPayCustomer.ExitTransferInfomationModelSerialNumberMacResponse retVal = ((IqSoft.CP.Integration.SDPayCustomer.CustomerSoap)(this)).ExitTransferInfomationModelSerialNumberMac(inValue);
            return retVal.ExitTransferInfomationModelSerialNumberMacResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<IqSoft.CP.Integration.SDPayCustomer.ExitTransferInfomationModelSerialNumberMacResponse> IqSoft.CP.Integration.SDPayCustomer.CustomerSoap.ExitTransferInfomationModelSerialNumberMacAsync(IqSoft.CP.Integration.SDPayCustomer.ExitTransferInfomationModelSerialNumberMacRequest request) {
            return base.Channel.ExitTransferInfomationModelSerialNumberMacAsync(request);
        }
        
        public System.Threading.Tasks.Task<IqSoft.CP.Integration.SDPayCustomer.ExitTransferInfomationModelSerialNumberMacResponse> ExitTransferInfomationModelSerialNumberMacAsync(string LoginAccount, string SerialNumber) {
            IqSoft.CP.Integration.SDPayCustomer.ExitTransferInfomationModelSerialNumberMacRequest inValue = new IqSoft.CP.Integration.SDPayCustomer.ExitTransferInfomationModelSerialNumberMacRequest();
            inValue.LoginAccount = LoginAccount;
            inValue.SerialNumber = SerialNumber;
            return ((IqSoft.CP.Integration.SDPayCustomer.CustomerSoap)(this)).ExitTransferInfomationModelSerialNumberMacAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        IqSoft.CP.Integration.SDPayCustomer.GetBalancesResponse IqSoft.CP.Integration.SDPayCustomer.CustomerSoap.GetBalances(IqSoft.CP.Integration.SDPayCustomer.GetBalancesRequest request) {
            return base.Channel.GetBalances(request);
        }
        
        public string GetBalances(string CardNum, string LoginName) {
            IqSoft.CP.Integration.SDPayCustomer.GetBalancesRequest inValue = new IqSoft.CP.Integration.SDPayCustomer.GetBalancesRequest();
            inValue.CardNum = CardNum;
            inValue.LoginName = LoginName;
            IqSoft.CP.Integration.SDPayCustomer.GetBalancesResponse retVal = ((IqSoft.CP.Integration.SDPayCustomer.CustomerSoap)(this)).GetBalances(inValue);
            return retVal.GetBalancesResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<IqSoft.CP.Integration.SDPayCustomer.GetBalancesResponse> IqSoft.CP.Integration.SDPayCustomer.CustomerSoap.GetBalancesAsync(IqSoft.CP.Integration.SDPayCustomer.GetBalancesRequest request) {
            return base.Channel.GetBalancesAsync(request);
        }
        
        public System.Threading.Tasks.Task<IqSoft.CP.Integration.SDPayCustomer.GetBalancesResponse> GetBalancesAsync(string CardNum, string LoginName) {
            IqSoft.CP.Integration.SDPayCustomer.GetBalancesRequest inValue = new IqSoft.CP.Integration.SDPayCustomer.GetBalancesRequest();
            inValue.CardNum = CardNum;
            inValue.LoginName = LoginName;
            return ((IqSoft.CP.Integration.SDPayCustomer.CustomerSoap)(this)).GetBalancesAsync(inValue);
        }
    }
}
