//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IqSoft.CP.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccessObject
    {
        public int Id { get; set; }
        public int ObjectTypeId { get; set; }
        public long ObjectId { get; set; }
        public int UserId { get; set; }
        public string PermissionId { get; set; }
    
        public virtual Permission Permission { get; set; }
    }
}
