//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IqSoft.CP.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class AffiliateCommission
    {
        public int Id { get; set; }
        public int AffiliateId { get; set; }
        public int CommissionType { get; set; }
        public string CurrencyId { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<int> ProductId { get; set; }
        public Nullable<decimal> Percent { get; set; }
        public Nullable<decimal> TotalDepositAmount { get; set; }
        public Nullable<bool> RequireVerification { get; set; }
        public Nullable<decimal> UpToAmount { get; set; }
        public Nullable<int> DepositCount { get; set; }
    
        public virtual Affiliate Affiliate { get; set; }
        public virtual Product Product { get; set; }
        public virtual Currency Currency { get; set; }
    }
}
