//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IqSoft.CP.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Banner
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Banner()
        {
            this.BannerSegmentSettings = new HashSet<BannerSegmentSetting>();
            this.BannerLanguageSettings = new HashSet<BannerLanguageSetting>();
        }
    
        public int Id { get; set; }
        public int PartnerId { get; set; }
        public int Type { get; set; }
        public string NickName { get; set; }
        public string Head { get; set; }
        public Nullable<long> HeadTranslationId { get; set; }
        public string Body { get; set; }
        public Nullable<long> BodyTranslationId { get; set; }
        public string Link { get; set; }
        public bool ShowDescription { get; set; }
        public int Order { get; set; }
        public bool IsEnabled { get; set; }
        public string Image { get; set; }
        public System.DateTime StartDate { get; set; }
        public System.DateTime EndDate { get; set; }
        public string Visibility { get; set; }
        public Nullable<int> ButtonType { get; set; }
    
        public virtual Partner Partner { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BannerSegmentSetting> BannerSegmentSettings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BannerLanguageSetting> BannerLanguageSettings { get; set; }
        public virtual Translation Translation { get; set; }
        public virtual Translation Translation1 { get; set; }
    }
}
