//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IqSoft.CP.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class BetShopGroup
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BetShopGroup()
        {
            this.BetShops = new HashSet<BetShop>();
            this.BetShopGroup1 = new HashSet<BetShopGroup>();
        }
    
        public int Id { get; set; }
        public Nullable<int> ParentId { get; set; }
        public int PartnerId { get; set; }
        public string Path { get; set; }
        public string Name { get; set; }
        public int State { get; set; }
        public bool IsLeaf { get; set; }
        public long SessionId { get; set; }
        public System.DateTime CreationTime { get; set; }
        public System.DateTime LastUpdateTime { get; set; }
        public Nullable<int> MaxCopyCount { get; set; }
        public Nullable<decimal> MaxWinAmount { get; set; }
        public Nullable<decimal> MinBetAmount { get; set; }
        public Nullable<int> MaxEventCountPerTicket { get; set; }
        public Nullable<int> CommissionType { get; set; }
        public Nullable<decimal> CommissionRate { get; set; }
        public Nullable<bool> AnonymousBet { get; set; }
        public Nullable<bool> AllowCashout { get; set; }
        public Nullable<bool> AllowLive { get; set; }
        public Nullable<bool> UsePin { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BetShop> BetShops { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BetShopGroup> BetShopGroup1 { get; set; }
        public virtual BetShopGroup BetShopGroup2 { get; set; }
        public virtual Partner Partner { get; set; }
        public virtual UserSession UserSession { get; set; }
    }
}
