//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IqSoft.CP.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class BetShopTicket
    {
        public long Id { get; set; }
        public long DocumentId { get; set; }
        public int GameId { get; set; }
        public long BarCode { get; set; }
        public int NumberOfPrints { get; set; }
        public Nullable<System.DateTime> LastPrintTime { get; set; }
        public System.DateTime CreationTime { get; set; }
    
        public virtual Product Product { get; set; }
    }
}
