//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IqSoft.CP.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class BetShop
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BetShop()
        {
            this.BetShopReconings = new HashSet<BetShopReconing>();
            this.CashDesks = new HashSet<CashDesk>();
            this.Accounts = new HashSet<Account>();
            this.PaymentRequests = new HashSet<PaymentRequest>();
        }
    
        public int Id { get; set; }
        public int GroupId { get; set; }
        public int Type { get; set; }
        public string Name { get; set; }
        public string CurrencyId { get; set; }
        public string Address { get; set; }
        public int RegionId { get; set; }
        public int PartnerId { get; set; }
        public int State { get; set; }
        public int DailyTicketNumber { get; set; }
        public decimal DefaultLimit { get; set; }
        public decimal CurrentLimit { get; set; }
        public long SessionId { get; set; }
        public System.DateTime CreationTime { get; set; }
        public System.DateTime LastUpdateTime { get; set; }
        public Nullable<decimal> BonusPercent { get; set; }
        public bool PrintLogo { get; set; }
        public string Ips { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<int> MaxCopyCount { get; set; }
        public Nullable<decimal> MaxWinAmount { get; set; }
        public Nullable<decimal> MinBetAmount { get; set; }
        public Nullable<int> MaxEventCountPerTicket { get; set; }
        public Nullable<int> CommissionType { get; set; }
        public Nullable<decimal> CommissionRate { get; set; }
        public Nullable<bool> AnonymousBet { get; set; }
        public Nullable<bool> AllowCashout { get; set; }
        public Nullable<bool> AllowLive { get; set; }
        public Nullable<bool> UsePin { get; set; }
        public string PaymentSystems { get; set; }
    
        public virtual BetShopGroup BetShopGroup { get; set; }
        public virtual Partner Partner { get; set; }
        public virtual User User { get; set; }
        public virtual UserSession UserSession { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BetShopReconing> BetShopReconings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CashDesk> CashDesks { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Account> Accounts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PaymentRequest> PaymentRequests { get; set; }
        public virtual Currency Currency { get; set; }
    }
}
