//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IqSoft.CP.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CashDeskShift
    {
        public int Id { get; set; }
        public int CashierId { get; set; }
        public int CashDeskId { get; set; }
        public System.DateTime StartTime { get; set; }
        public Nullable<System.DateTime> EndTime { get; set; }
        public decimal StartAmount { get; set; }
        public Nullable<decimal> EndAmount { get; set; }
        public decimal BetAmount { get; set; }
        public decimal PayedWinAmount { get; set; }
        public decimal DepositAmount { get; set; }
        public decimal WithdrawAmount { get; set; }
        public decimal DebitCorrectionAmount { get; set; }
        public decimal CreditCorrectionAmount { get; set; }
        public decimal BonusAmount { get; set; }
        public int State { get; set; }
        public Nullable<int> Number { get; set; }
    
        public virtual CashDesk CashDesk { get; set; }
        public virtual User User { get; set; }
    }
}
