//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IqSoft.CP.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClientBonu
    {
        public int Id { get; set; }
        public int BonusId { get; set; }
        public int ClientId { get; set; }
        public int Status { get; set; }
        public decimal BonusPrize { get; set; }
        public System.DateTime CreationTime { get; set; }
        public Nullable<System.DateTime> AwardingTime { get; set; }
        public Nullable<decimal> TurnoverAmountLeft { get; set; }
        public Nullable<decimal> FinalAmount { get; set; }
        public Nullable<System.DateTime> CalculationTime { get; set; }
        public Nullable<System.DateTime> ValidUntil { get; set; }
        public Nullable<int> TriggerId { get; set; }
        public Nullable<long> CreationDate { get; set; }
        public Nullable<long> ReuseNumber { get; set; }
        public Nullable<bool> Considered { get; set; }
    
        public virtual Bonu Bonu { get; set; }
        public virtual Client Client { get; set; }
        public virtual TriggerSetting TriggerSetting { get; set; }
    }
}
