//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IqSoft.CP.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClientSetting
    {
        public int Id { get; set; }
        public int ClientId { get; set; }
        public string Name { get; set; }
        public Nullable<decimal> NumericValue { get; set; }
        public string StringValue { get; set; }
        public Nullable<System.DateTime> DateValue { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<System.DateTime> CreationTime { get; set; }
        public Nullable<System.DateTime> LastUpdateTime { get; set; }
    
        public virtual User User { get; set; }
        public virtual Client Client { get; set; }
    }
}
