//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IqSoft.CP.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClientIdentity
    {
        public int Id { get; set; }
        public int ClientId { get; set; }
        public Nullable<int> UserId { get; set; }
        public int DocumentTypeId { get; set; }
        public string ImagePath { get; set; }
        public int Status { get; set; }
        public System.DateTime CreationTime { get; set; }
        public System.DateTime LastUpdateTime { get; set; }
        public Nullable<System.DateTime> ExpirationTime { get; set; }
        public Nullable<long> ExpirationDate { get; set; }
    
        public virtual User User { get; set; }
        public virtual Client Client { get; set; }
    }
}
