//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IqSoft.CP.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClientClosedPeriod
    {
        public long Id { get; set; }
        public int ClientId { get; set; }
        public System.DateTime Date { get; set; }
        public decimal TotalBetAmount { get; set; }
        public decimal TotalWinAmount { get; set; }
        public decimal TotalGGR { get; set; }
        public decimal TotalNetGaming { get; set; }
        public decimal TotalDepositAmount { get; set; }
        public decimal TotalWithdrawAmount { get; set; }
        public decimal TotalCreditCorrection { get; set; }
        public decimal TotalDebitCorrection { get; set; }
    
        public virtual Client Client { get; set; }
    }
}
