//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IqSoft.CP.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClientInfo
    {
        public long Id { get; set; }
        public Nullable<int> PartnerId { get; set; }
        public Nullable<int> ObjectId { get; set; }
        public Nullable<int> ObjectTypeId { get; set; }
        public int Type { get; set; }
        public string Data { get; set; }
        public System.DateTime CreationTime { get; set; }
        public int State { get; set; }
        public string MobileOrEmail { get; set; }
        public string Ip { get; set; }
    
        public virtual ObjectType ObjectType { get; set; }
        public virtual Partner Partner { get; set; }
    }
}
