//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IqSoft.NGGP.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClosedPeriod
    {
        public long Id { get; set; }
        public long AccountId { get; set; }
        public System.DateTime Date { get; set; }
        public decimal Deposit { get; set; }
        public decimal Withdraw { get; set; }
        public decimal TransferIn { get; set; }
        public decimal TransferOut { get; set; }
        public decimal FirstBalance { get; set; }
        public decimal LastBalance { get; set; }
    
        public virtual Account Account { get; set; }
    }
}
