//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IqSoft.CP.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Email
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Email()
        {
            this.ClientMessages = new HashSet<ClientMessage>();
        }
    
        public int Id { get; set; }
        public int PartnerId { get; set; }
        public string Receiver { get; set; }
        public int Status { get; set; }
        public string Subject { get; set; }
        public string Body { get; set; }
        public Nullable<int> MessageTemplateId { get; set; }
        public Nullable<System.DateTime> CreationTime { get; set; }
        public Nullable<long> ObjectId { get; set; }
        public Nullable<int> ObjectTypeId { get; set; }
    
        public virtual MessageTemplate MessageTemplate { get; set; }
        public virtual Partner Partner { get; set; }
        public virtual ObjectType ObjectType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ClientMessage> ClientMessages { get; set; }
    }
}
