//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IqSoft.CP.DAL
{
    using System;
    
    public partial class fnAgentTurnoverProfit
    {
        public int RecieverAgentId { get; set; }
        public string RecieverAgentPath { get; set; }
        public int AgentId { get; set; }
        public int ProductId { get; set; }
        public Nullable<int> ProductGroupId { get; set; }
        public string ProductGroupName { get; set; }
        public Nullable<int> SelectionsCount { get; set; }
        public Nullable<decimal> TotalBetAmount { get; set; }
        public Nullable<decimal> TotalWinAmount { get; set; }
        public string TurnoverPercent { get; set; }
    }
}
