//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IqSoft.CP.DAL
{
    using System;
    
    public partial class fnBanner
    {
        public int Id { get; set; }
        public int PartnerId { get; set; }
        public int Type { get; set; }
        public string NickName { get; set; }
        public string Link { get; set; }
        public bool ShowDescription { get; set; }
        public Nullable<int> ButtonType { get; set; }
        public int Order { get; set; }
        public bool IsEnabled { get; set; }
        public string Image { get; set; }
        public System.DateTime StartDate { get; set; }
        public string Visibility { get; set; }
        public System.DateTime EndDate { get; set; }
        public string Head { get; set; }
        public string Body { get; set; }
    }
}
