//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IqSoft.CP.DAL
{
    using System;
    
    public partial class fnBetShopBet
    {
        public long BetDocumentId { get; set; }
        public Nullable<int> BetExternalTransactionId { get; set; }
        public string BetShopCurrencyId { get; set; }
        public Nullable<int> BetInfo { get; set; }
        public Nullable<int> CashDeskId { get; set; }
        public int BetTypeId { get; set; }
        public decimal PossibleWin { get; set; }
        public int ProductId { get; set; }
        public Nullable<int> GameProviderId { get; set; }
        public Nullable<int> TicketInfo { get; set; }
        public Nullable<int> CashierId { get; set; }
        public int BetShopGroupId { get; set; }
        public System.DateTime BetDate { get; set; }
        public Nullable<System.DateTime> PayDate { get; set; }
        public int BetShopId { get; set; }
        public string BetShopName { get; set; }
        public decimal BetAmount { get; set; }
        public string CurrencyId { get; set; }
        public Nullable<long> TicketNumber { get; set; }
        public int PartnerId { get; set; }
        public string ProductName { get; set; }
        public Nullable<int> RoundId { get; set; }
        public string ProviderName { get; set; }
        public bool HasNote { get; set; }
        public int State { get; set; }
        public Nullable<System.DateTime> WinDate { get; set; }
        public decimal WinAmount { get; set; }
        public long Date { get; set; }
        public Nullable<int> AgentId { get; set; }
    }
}
