//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IqSoft.CP.DAL
{
    using System;
    
    public partial class fnBetShops
    {
        public int Id { get; set; }
        public int GroupId { get; set; }
        public string Name { get; set; }
        public string CurrencyId { get; set; }
        public string Address { get; set; }
        public int PartnerId { get; set; }
        public int State { get; set; }
        public int DailyTicketNumber { get; set; }
        public decimal DefaultLimit { get; set; }
        public decimal CurrentLimit { get; set; }
        public long SessionId { get; set; }
        public System.DateTime CreationTime { get; set; }
        public System.DateTime LastUpdateTime { get; set; }
        public Nullable<int> AgentId { get; set; }
        public string GroupName { get; set; }
        public string PartnerName { get; set; }
        public decimal Balance { get; set; }
        public Nullable<int> MaxCopyCount { get; set; }
        public Nullable<decimal> MaxWinAmount { get; set; }
        public Nullable<decimal> MinBetAmount { get; set; }
        public Nullable<int> MaxEventCountPerTicket { get; set; }
        public Nullable<int> CommissionType { get; set; }
        public Nullable<decimal> CommissionRate { get; set; }
        public Nullable<bool> AnonymousBet { get; set; }
        public Nullable<bool> AllowCashout { get; set; }
        public Nullable<bool> AllowLive { get; set; }
        public Nullable<bool> UsePin { get; set; }
        public string Ips { get; set; }
    }
}
