//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IqSoft.CP.DAL
{
    using System;
    
    public partial class fnCashDeskTransaction
    {
        public long Id { get; set; }
        public string ExternalTransactionId { get; set; }
        public decimal Amount { get; set; }
        public string CurrencyId { get; set; }
        public int State { get; set; }
        public string Info { get; set; }
        public Nullable<int> Creator { get; set; }
        public Nullable<int> CashDeskId { get; set; }
        public Nullable<long> TicketNumber { get; set; }
        public string TicketInfo { get; set; }
        public Nullable<int> CashierId { get; set; }
        public System.DateTime CreationTime { get; set; }
        public string OperationTypeName { get; set; }
        public string CashDeskName { get; set; }
        public string BetShopName { get; set; }
        public int BetShopId { get; set; }
        public int PartnerId { get; set; }
        public int OperationTypeId { get; set; }
        public Nullable<long> Date { get; set; }
        public Nullable<int> ClientId { get; set; }
        public Nullable<long> PaymentRequestId { get; set; }
        public Nullable<decimal> CommissionAmount { get; set; }
    }
}
