//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IqSoft.CP.DAL
{
    using System;
    
    public partial class fnClientReport
    {
        public Nullable<int> ClientId { get; set; }
        public string UserName { get; set; }
        public int PartnerId { get; set; }
        public string CurrencyId { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Email { get; set; }
        public Nullable<int> AffiliatePlatformId { get; set; }
        public string AffiliateId { get; set; }
        public string AffiliateReferralId { get; set; }
        public Nullable<decimal> TotalWithdrawalAmount { get; set; }
        public Nullable<int> WithdrawalsCount { get; set; }
        public Nullable<decimal> TotalDepositAmount { get; set; }
        public Nullable<int> DepositsCount { get; set; }
        public Nullable<decimal> TotalBetAmount { get; set; }
        public Nullable<int> BetsCount { get; set; }
        public Nullable<decimal> TotalWinAmount { get; set; }
        public Nullable<int> WinsCount { get; set; }
        public Nullable<decimal> GGR { get; set; }
        public Nullable<decimal> TotalDebitCorrection { get; set; }
        public Nullable<int> DebitCorrectionsCount { get; set; }
        public Nullable<decimal> TotalCreditCorrection { get; set; }
        public Nullable<int> CreditCorrectionsCount { get; set; }
    }
}
