//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IqSoft.CP.DAL
{
    using System;
    
    public partial class fnClientLog
    {
        public long Id { get; set; }
        public int Action { get; set; }
        public int ClientId { get; set; }
        public Nullable<int> UserId { get; set; }
        public string Ip { get; set; }
        public string Page { get; set; }
        public System.DateTime CreationTime { get; set; }
        public Nullable<long> ClientSessionId { get; set; }
        public string UserFirstName { get; set; }
        public string UserLastName { get; set; }
    }
}
