//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IqSoft.CP.DAL
{
    using System;
    
    public partial class fnClientIdentity
    {
        public int Id { get; set; }
        public int PartnerId { get; set; }
        public int ClientId { get; set; }
        public string UserName { get; set; }
        public string ImagePath { get; set; }
        public Nullable<int> UserId { get; set; }
        public string UserFirstName { get; set; }
        public string UserLastName { get; set; }
        public System.DateTime CreationTime { get; set; }
        public System.DateTime LastUpdateTime { get; set; }
        public int DocumentTypeId { get; set; }
        public int Status { get; set; }
        public Nullable<System.DateTime> ExpirationTime { get; set; }
        public Nullable<long> ExpirationDate { get; set; }
        public Nullable<bool> HasNote { get; set; }
    }
}
