//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IqSoft.CP.DAL
{
    using System;
    
    public partial class fnClientBonus
    {
        public int Id { get; set; }
        public int BonusId { get; set; }
        public int ClientId { get; set; }
        public int Status { get; set; }
        public decimal BonusPrize { get; set; }
        public Nullable<decimal> SpinsCount { get; set; }
        public System.DateTime CreationTime { get; set; }
        public Nullable<System.DateTime> AwardingTime { get; set; }
        public Nullable<decimal> TurnoverAmountLeft { get; set; }
        public Nullable<decimal> RemainingCredit { get; set; }
        public Nullable<decimal> WageringTarget { get; set; }
        public Nullable<decimal> FinalAmount { get; set; }
        public Nullable<System.DateTime> CalculationTime { get; set; }
        public Nullable<System.DateTime> ValidUntil { get; set; }
        public Nullable<int> LinkedBonusId { get; set; }
        public Nullable<long> CreationDate { get; set; }
        public Nullable<long> ReuseNumber { get; set; }
        public string UserName { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string CurrencyId { get; set; }
        public string Email { get; set; }
        public string MobileNumber { get; set; }
        public string NickName { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public int PartnerId { get; set; }
        public Nullable<int> FinalAccountTypeId { get; set; }
        public int BonusStatus { get; set; }
        public System.DateTime StartTime { get; set; }
        public System.DateTime FinishTime { get; set; }
        public System.DateTime LastExecutionTime { get; set; }
        public int Period { get; set; }
        public int Type { get; set; }
        public string Info { get; set; }
        public Nullable<int> TurnoverCount { get; set; }
        public Nullable<decimal> MinAmount { get; set; }
        public Nullable<decimal> MaxAmount { get; set; }
        public Nullable<int> Sequence { get; set; }
        public Nullable<int> Priority { get; set; }
        public Nullable<int> WinAccountTypeId { get; set; }
        public Nullable<int> ValidForAwarding { get; set; }
        public Nullable<int> ValidForSpending { get; set; }
        public Nullable<int> ReusingMaxCount { get; set; }
        public Nullable<bool> ResetOnWithdraw { get; set; }
        public Nullable<System.DateTime> BonusCreationTime { get; set; }
        public Nullable<System.DateTime> BonusLastUpdateTime { get; set; }
        public Nullable<bool> AllowSplit { get; set; }
        public Nullable<bool> RefundRollbacked { get; set; }
        public string Condition { get; set; }
    }
}
