//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IqSoft.CP.DAL
{
    using System;
    
    public partial class fnClient
    {
        public int Id { get; set; }
        public string Email { get; set; }
        public bool IsEmailVerified { get; set; }
        public string CurrencyId { get; set; }
        public string UserName { get; set; }
        public string NickName { get; set; }
        public string PasswordHash { get; set; }
        public int Salt { get; set; }
        public int PartnerId { get; set; }
        public int Gender { get; set; }
        public System.DateTime BirthDate { get; set; }
        public Nullable<int> Age { get; set; }
        public bool SendMail { get; set; }
        public bool SendSms { get; set; }
        public bool CallToPhone { get; set; }
        public bool SendPromotions { get; set; }
        public int State { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string RegionIsoCode { get; set; }
        public int RegionId { get; set; }
        public Nullable<int> CountryId { get; set; }
        public string Info { get; set; }
        public string ZipCode { get; set; }
        public string RegistrationIp { get; set; }
        public string DocumentNumber { get; set; }
        public string DocumentIssuedBy { get; set; }
        public bool IsDocumentVerified { get; set; }
        public string Address { get; set; }
        public string MobileNumber { get; set; }
        public string PhoneNumber { get; set; }
        public bool IsMobileNumberVerified { get; set; }
        public bool HasNote { get; set; }
        public string LanguageId { get; set; }
        public string City { get; set; }
        public System.DateTime CreationTime { get; set; }
        public System.DateTime LastUpdateTime { get; set; }
        public Nullable<System.DateTime> FirstDepositDate { get; set; }
        public Nullable<System.DateTime> LastDepositDate { get; set; }
        public Nullable<decimal> LastDepositAmount { get; set; }
        public int CategoryId { get; set; }
        public Nullable<int> DocumentType { get; set; }
        public Nullable<int> AffiliatePlatformId { get; set; }
        public string AffiliateId { get; set; }
        public string AffiliateReferralId { get; set; }
        public Nullable<System.DateTime> LastSessionDate { get; set; }
        public Nullable<long> LastSessionId { get; set; }
        public string SecondName { get; set; }
        public string SecondSurname { get; set; }
        public string UnderMonitoringTypes { get; set; }
        public Nullable<decimal> BonusBalance { get; set; }
        public Nullable<decimal> RealBalance { get; set; }
        public int GGR { get; set; }
        public int NETGaming { get; set; }
        public string UserPath { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<int> Title { get; set; }
    }
}
