//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IqSoft.NGGP.DAL
{
    using System;
    
    public partial class fnDepositToInternetClient
    {
        public long Id { get; set; }
        public string ExternalTransactionId { get; set; }
        public decimal Amount { get; set; }
        public string CurrencyId { get; set; }
        public int State { get; set; }
        public int OperationTypeId { get; set; }
        public Nullable<long> ParentId { get; set; }
        public Nullable<long> PaymentRequestId { get; set; }
        public string Info { get; set; }
        public Nullable<int> Creator { get; set; }
        public Nullable<int> CashDeskId { get; set; }
        public Nullable<int> PartnerPaymentSettingId { get; set; }
        public Nullable<int> PartnerProductId { get; set; }
        public Nullable<int> GameProviderId { get; set; }
        public Nullable<int> ClientId { get; set; }
        public Nullable<long> ExternalOperationId { get; set; }
        public Nullable<long> TicketNumber { get; set; }
        public string TicketInfo { get; set; }
        public Nullable<int> UserId { get; set; }
        public long SessionId { get; set; }
        public System.DateTime CreationTime { get; set; }
        public System.DateTime LastUpdateTime { get; set; }
        public int PartnerId { get; set; }
        public string ClientLastName { get; set; }
        public string ClientFirstName { get; set; }
        public string ClientUserName { get; set; }
        public string PaymentSystemName { get; set; }
        public int PaymentSystemId { get; set; }
        public Nullable<int> BetShopId { get; set; }
        public string BetShopName { get; set; }
    }
}
