//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IqSoft.CP.DAL
{
    using System;
    
    public partial class fnFirstTimePaymentRequest
    {
        public long Id { get; set; }
        public int PartnerId { get; set; }
        public int ClientId { get; set; }
        public decimal Amount { get; set; }
        public string CurrencyId { get; set; }
        public int Status { get; set; }
        public Nullable<int> PartnerPaymentSettingId { get; set; }
        public Nullable<int> BetShopId { get; set; }
        public Nullable<int> CashDeskId { get; set; }
        public Nullable<int> CashierId { get; set; }
        public string Parameters { get; set; }
        public int PaymentSystemId { get; set; }
        public string Info { get; set; }
        public int Type { get; set; }
        public string ExternalTransactionId { get; set; }
        public Nullable<long> SessionId { get; set; }
        public System.DateTime CreationTime { get; set; }
        public System.DateTime LastUpdateTime { get; set; }
        public string PaymentSystemName { get; set; }
    }
}
