//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IqSoft.CP.DAL
{
    using System;
    
    public partial class fnInternetBetForDashboard
    {
        public string CurrencyId { get; set; }
        public int DeviceTypeId { get; set; }
        public Nullable<int> GameProviderId { get; set; }
        public Nullable<decimal> TotalBetAmount { get; set; }
        public Nullable<decimal> BetShopTotalBetAmount { get; set; }
        public Nullable<decimal> TotalBonusBetAmount { get; set; }
        public Nullable<decimal> BetShopTotalBonusBetAmount { get; set; }
        public Nullable<decimal> TotalWinAmount { get; set; }
        public Nullable<decimal> BetShopTotalWinAmount { get; set; }
        public Nullable<decimal> TotalBonusWinAmount { get; set; }
        public Nullable<decimal> BetShopTotalBonusWinAmount { get; set; }
        public Nullable<int> TotalCount { get; set; }
        public Nullable<int> TotalPlayersCount { get; set; }
    }
}
