//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IqSoft.CP.DAL
{
    using System;
    
    public partial class fnPartnerCountrySetting
    {
        public int Id { get; set; }
        public int PartnerId { get; set; }
        public int Type { get; set; }
        public int RegionId { get; set; }
        public string CountryNickName { get; set; }
        public string CountryName { get; set; }
        public string IsoCode { get; set; }
        public string IsoCode3 { get; set; }
    }
}
