//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IqSoft.NGGP.DAL
{
    using System;
    
    public partial class fnPartnerSetting
    {
        public int PartnerId { get; set; }
        public Nullable<int> ClientMinAge { get; set; }
        public string PasswordRegExp { get; set; }
        public Nullable<int> VerificationType { get; set; }
        public Nullable<int> VerificationCodeLength { get; set; }
        public Nullable<int> UserSessionExpireTime { get; set; }
        public Nullable<int> UnpaidWinValidPeriod { get; set; }
        public Nullable<int> VerificationKeyAciteMinutes { get; set; }
    }
}
