//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IqSoft.CP.DAL
{
    using System;
    
    public partial class fnPartnerProductSetting
    {
        public int Id { get; set; }
        public int PartnerId { get; set; }
        public int ProductId { get; set; }
        public decimal Percent { get; set; }
        public int State { get; set; }
        public Nullable<decimal> Rating { get; set; }
        public string CategoryIds { get; set; }
        public Nullable<int> OpenMode { get; set; }
        public Nullable<bool> HasDemo { get; set; }
        public string ProductNickName { get; set; }
        public string ProductExternalId { get; set; }
        public string ProductName { get; set; }
        public int ProductIsLeaf { get; set; }
        public Nullable<int> ProductGameProviderId { get; set; }
        public Nullable<int> ProductParentId { get; set; }
        public Nullable<int> PaymentSystemId { get; set; }
        public string GameProviderName { get; set; }
        public Nullable<int> SubproviderId { get; set; }
        public string SubproviderName { get; set; }
        public bool IsForDesktop { get; set; }
        public bool IsForMobile { get; set; }
        public string Jackpot { get; set; }
        public string MobileImageUrl { get; set; }
        public string WebImageUrl { get; set; }
        public Nullable<bool> HasImages { get; set; }
        public int ProductState { get; set; }
        public Nullable<decimal> RTP { get; set; }
        public Nullable<int> Volatility { get; set; }
        public System.DateTime CreationTime { get; set; }
        public System.DateTime LastUpdateTime { get; set; }
    }
}
