//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IqSoft.CP.DAL
{
    using System;
    
    public partial class fnRegion
    {
        public int Id { get; set; }
        public Nullable<int> ParentId { get; set; }
        public int TypeId { get; set; }
        public string IsoCode { get; set; }
        public string IsoCode3 { get; set; }
        public int State { get; set; }
        public string CurrencyId { get; set; }
        public string Name { get; set; }
        public string LanguageId { get; set; }
        public string Info { get; set; }
        public string NickName { get; set; }
        public string Path { get; set; }
    }
}
