//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IqSoft.CP.DAL
{
    using System;
    
    public partial class fnReportByPaymentSystem
    {
        public int PartnerId { get; set; }
        public string PartnerName { get; set; }
        public int PaymentSystemId { get; set; }
        public string PaymentSystemName { get; set; }
        public int Status { get; set; }
        public Nullable<int> Count { get; set; }
        public Nullable<decimal> TotalAmount { get; set; }
    }
}
