//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IqSoft.CP.DAL
{
    using System;
    
    public partial class fnReportByProduct
    {
        public int ClientId { get; set; }
        public int PartnerId { get; set; }
        public string ClientFirstName { get; set; }
        public string ClientLastName { get; set; }
        public string Currency { get; set; }
        public int CategoryId { get; set; }
        public int ProductId { get; set; }
        public string ProductName { get; set; }
        public Nullable<int> DeviceTypeId { get; set; }
        public string ProviderName { get; set; }
        public string AffiliateId { get; set; }
        public Nullable<decimal> TotalBetsAmount { get; set; }
        public Nullable<decimal> TotalWinsAmount { get; set; }
        public Nullable<int> TotalBetsCount { get; set; }
        public Nullable<int> TotalUncalculatedBetsCount { get; set; }
        public Nullable<decimal> TotalUncalculatedBetsAmount { get; set; }
        public Nullable<decimal> GGR { get; set; }
        public Nullable<int> AffiliateReferralId { get; set; }
    }
}
