//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IqSoft.CP.DAL
{
    using System;
    
    public partial class fnReportByBetShopOperation
    {
        public int Id { get; set; }
        public int PartnerId { get; set; }
        public int GroupId { get; set; }
        public string Name { get; set; }
        public string Address { get; set; }
        public Nullable<int> TotalPandingDepositsCount { get; set; }
        public Nullable<decimal> TotalPandingDepositsAmount { get; set; }
        public Nullable<int> TotalPayedDepositsCount { get; set; }
        public Nullable<decimal> TotalPayedDepositsAmount { get; set; }
        public Nullable<int> TotalCanceledDepositsCount { get; set; }
        public Nullable<decimal> TotalCanceledDepositsAmount { get; set; }
        public Nullable<int> TotalPandingWithdrawalsCount { get; set; }
        public Nullable<decimal> TotalPandingWithdrawalsAmount { get; set; }
        public Nullable<int> TotalPayedWithdrawalsCount { get; set; }
        public Nullable<decimal> TotalPayedWithdrawalsAmount { get; set; }
        public Nullable<int> TotalCanceledWithdrawalsCount { get; set; }
        public Nullable<decimal> TotalCanceledWithdrawalsAmount { get; set; }
    }
}
