//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IqSoft.CP.DAL
{
    using System;
    
    public partial class fnShiftReport
    {
        public decimal BetAmount { get; set; }
        public decimal WinAmount { get; set; }
        public decimal CalculatedBetAmount { get; set; }
        public decimal PayedWin { get; set; }
        public decimal DepositToInternetClient { get; set; }
        public decimal WithdrawFromInternetClient { get; set; }
        public decimal DebitCorrectionOnCashDesk { get; set; }
        public decimal CreditCorrectionOnCashDesk { get; set; }
    }
}
