//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IqSoft.CP.DAL
{
    using System;
    
    public partial class fnTicket
    {
        public long Id { get; set; }
        public Nullable<int> ClientId { get; set; }
        public string UserName { get; set; }
        public int PartnerId { get; set; }
        public string Subject { get; set; }
        public int Status { get; set; }
        public int Type { get; set; }
        public Nullable<int> UserUnreadMessagesCount { get; set; }
        public System.DateTime CreationTime { get; set; }
        public long LastMessageDate { get; set; }
        public System.DateTime LastMessageTime { get; set; }
        public Nullable<int> AffiliateReferralId { get; set; }
        public Nullable<int> UserId { get; set; }
        public string UserFirstName { get; set; }
        public string UserLastName { get; set; }
        public string ClientPath { get; set; }
        public string AffiliateId { get; set; }
    }
}
