//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IqSoft.CP.DAL
{
    using System;
    
    public partial class fnTransaction
    {
        public long Id { get; set; }
        public long DocumentId { get; set; }
        public long AccountId { get; set; }
        public decimal Amount { get; set; }
        public int OperationTypeId { get; set; }
        public int Type { get; set; }
        public System.DateTime CreationTime { get; set; }
        public Nullable<long> Date { get; set; }
        public Nullable<int> CashDeskId { get; set; }
        public Nullable<int> Creator { get; set; }
        public string ExternalTransactionId { get; set; }
        public string Info { get; set; }
        public Nullable<long> DocumentParentId { get; set; }
        public Nullable<int> PartnerPaymentSettingId { get; set; }
        public string CurrencyId { get; set; }
        public Nullable<long> PaymentRequestId { get; set; }
        public int DocumentState { get; set; }
        public long ObjectId { get; set; }
        public int ObjectTypeId { get; set; }
        public int AccountTypeId { get; set; }
        public string AccountCurrencyId { get; set; }
        public Nullable<int> ClientId { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<long> ExternalOperationId { get; set; }
        public Nullable<int> GameProviderId { get; set; }
        public string OperationTypeName { get; set; }
        public string PaymentSystemName { get; set; }
        public string ProductName { get; set; }
        public string GameProviderName { get; set; }
    }
}
