//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IqSoft.CP.DAL
{
    using System;
    
    public partial class fnUserPermission
    {
        public int UserId { get; set; }
        public string PermissionId { get; set; }
        public bool IsForAll { get; set; }
        public bool IsAdmin { get; set; }
    }
}
