//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IqSoft.CP.DAL
{
    using System;
    
    public partial class fnVipLevel
    {
        public int Id { get; set; }
        public long DescriptionTranslationId { get; set; }
        public int Number { get; set; }
        public int ActivePlayersCount { get; set; }
        public decimal MonthlyGGR { get; set; }
        public decimal SportsbookGGR { get; set; }
        public decimal OverdueObligations { get; set; }
        public string Description { get; set; }
    }
}
