//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IqSoft.CP.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class JobResult
    {
        public long Id { get; set; }
        public int JobId { get; set; }
        public System.DateTime ExecutionTime { get; set; }
        public int Duration { get; set; }
        public string Message { get; set; }
    
        public virtual Job Job { get; set; }
    }
}
