//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IqSoft.CP.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Merchant
    {
        public int Id { get; set; }
        public int PartnerId { get; set; }
        public string MerchantKey { get; set; }
        public string MerchantUrl { get; set; }
    
        public virtual Partner Partner { get; set; }
    }
}
