//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IqSoft.CP.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class News
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public News()
        {
            this.News1 = new HashSet<News>();
            this.NewsLanguageSettings = new HashSet<NewsLanguageSetting>();
            this.NewsSegmentSettings = new HashSet<NewsSegmentSetting>();
        }
    
        public int Id { get; set; }
        public int PartnerId { get; set; }
        public string NickName { get; set; }
        public long TitleTranslationId { get; set; }
        public long DescriptionTranslationId { get; set; }
        public long ContentTranslationId { get; set; }
        public int Type { get; set; }
        public string ImageName { get; set; }
        public int State { get; set; }
        public System.DateTime CreationTime { get; set; }
        public System.DateTime LastUpdateTime { get; set; }
        public System.DateTime StartDate { get; set; }
        public System.DateTime FinishDate { get; set; }
        public int Order { get; set; }
        public Nullable<int> ParentId { get; set; }
        public string StyleType { get; set; }
    
        public virtual Translation Translation { get; set; }
        public virtual Translation Translation1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<News> News1 { get; set; }
        public virtual News News2 { get; set; }
        public virtual Partner Partner { get; set; }
        public virtual Translation Translation2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NewsLanguageSetting> NewsLanguageSettings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NewsSegmentSetting> NewsSegmentSettings { get; set; }
    }
}
