//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IqSoft.CP.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class NotificationTrigger
    {
        public int Id { get; set; }
        public int TriggerType { get; set; }
        public int PartnerId { get; set; }
        public Nullable<int> AffiliatePlatformId { get; set; }
        public string AffiliateId { get; set; }
        public string ClickId { get; set; }
        public int ClientId { get; set; }
        public string CurrencyId { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<int> DepositCount { get; set; }
        public string TransactionId { get; set; }
        public int State { get; set; }
        public System.DateTime CreationDate { get; set; }
        public System.DateTime LastUpdateDate { get; set; }
        public string Reason { get; set; }
    
        public virtual AffiliatePlatform AffiliatePlatform { get; set; }
    }
}
