//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IqSoft.CP.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ObjectDataChangeHistory
    {
        public long Id { get; set; }
        public int UserId { get; set; }
        public long ObjectId { get; set; }
        public int ObjectTypeId { get; set; }
        public string FieldName { get; set; }
        public string StringValue { get; set; }
        public Nullable<decimal> NumericValue { get; set; }
        public System.DateTime CreationTime { get; set; }
    
        public virtual ObjectType ObjectType { get; set; }
        public virtual User User { get; set; }
    }
}
