//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IqSoft.CP.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ObjectChangeHistory
    {
        public long Id { get; set; }
        public long ObjectId { get; set; }
        public int ObjectTypeId { get; set; }
        public string Object { get; set; }
        public Nullable<long> SessionId { get; set; }
        public System.DateTime ChangeDate { get; set; }
        public string Comment { get; set; }
    
        public virtual ObjectType ObjectType { get; set; }
        public virtual UserSession UserSession { get; set; }
    }
}
