//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IqSoft.CP.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class PartnerBankInfo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PartnerBankInfo()
        {
            this.ClientBankInfoes = new HashSet<ClientBankInfo>();
        }
    
        public int Id { get; set; }
        public int PartnerId { get; set; }
        public Nullable<int> PaymentSystemId { get; set; }
        public string BankName { get; set; }
        public string BankCode { get; set; }
        public string OwnerName { get; set; }
        public string BranchName { get; set; }
        public string IBAN { get; set; }
        public string AccountNumber { get; set; }
        public string CurrencyId { get; set; }
        public bool Active { get; set; }
        public System.DateTime CreationTime { get; set; }
        public System.DateTime LastUpdateTime { get; set; }
        public int Type { get; set; }
        public long TranslationId { get; set; }
        public int Order { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ClientBankInfo> ClientBankInfoes { get; set; }
        public virtual Partner Partner { get; set; }
        public virtual Translation Translation { get; set; }
        public virtual PaymentSystem PaymentSystem { get; set; }
        public virtual Currency Currency { get; set; }
    }
}
