//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IqSoft.CP.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class PartnerPaymentSetting
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PartnerPaymentSetting()
        {
            this.ClientPaymentInfoes = new HashSet<ClientPaymentInfo>();
            this.ClientPaymentSettings = new HashSet<ClientPaymentSetting>();
            this.Documents = new HashSet<Document>();
            this.PartnerPaymentCountrySettings = new HashSet<PartnerPaymentCountrySetting>();
            this.PartnerPaymentCurrencyRates = new HashSet<PartnerPaymentCurrencyRate>();
            this.PaymentRequests = new HashSet<PaymentRequest>();
        }
    
        public int Id { get; set; }
        public int PartnerId { get; set; }
        public int PaymentSystemId { get; set; }
        public decimal Commission { get; set; }
        public decimal FixedFee { get; set; }
        public int State { get; set; }
        public string CurrencyId { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public long SessionId { get; set; }
        public System.DateTime CreationTime { get; set; }
        public System.DateTime LastUpdateTime { get; set; }
        public int PaymentSystemPriority { get; set; }
        public int Type { get; set; }
        public string Info { get; set; }
        public decimal MinAmount { get; set; }
        public decimal MaxAmount { get; set; }
        public Nullable<bool> AllowMultipleClientsPerPaymentInfo { get; set; }
        public Nullable<bool> AllowMultiplePaymentInfoes { get; set; }
        public Nullable<int> OpenMode { get; set; }
        public string OSTypes { get; set; }
        public Nullable<decimal> ApplyPercentAmount { get; set; }
        public string ImageExtension { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ClientPaymentInfo> ClientPaymentInfoes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ClientPaymentSetting> ClientPaymentSettings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Document> Documents { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PartnerPaymentCountrySetting> PartnerPaymentCountrySettings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PartnerPaymentCurrencyRate> PartnerPaymentCurrencyRates { get; set; }
        public virtual PaymentSystem PaymentSystem { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PaymentRequest> PaymentRequests { get; set; }
    }
}
