//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IqSoft.CP.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class PaymentRequestHistory
    {
        public long Id { get; set; }
        public long RequestId { get; set; }
        public int Status { get; set; }
        public string Comment { get; set; }
        public Nullable<long> SessionId { get; set; }
        public System.DateTime CreationTime { get; set; }
    
        public virtual UserSession UserSession { get; set; }
        public virtual PaymentRequest PaymentRequest { get; set; }
    }
}
