//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IqSoft.CP.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class PaymentRequest
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PaymentRequest()
        {
            this.JobTriggers = new HashSet<JobTrigger>();
            this.PaymentRequest1 = new HashSet<PaymentRequest>();
            this.PaymentRequestHistories = new HashSet<PaymentRequestHistory>();
            this.PaymentRequestTransfers = new HashSet<PaymentRequestTransfer>();
        }
    
        public long Id { get; set; }
        public Nullable<int> ClientId { get; set; }
        public decimal Amount { get; set; }
        public string CurrencyId { get; set; }
        public int Status { get; set; }
        public Nullable<int> PartnerPaymentSettingId { get; set; }
        public Nullable<int> BetShopId { get; set; }
        public Nullable<int> CashDeskId { get; set; }
        public Nullable<int> CashierId { get; set; }
        public string Parameters { get; set; }
        public int PaymentSystemId { get; set; }
        public string Info { get; set; }
        public int Type { get; set; }
        public string ExternalTransactionId { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<long> SessionId { get; set; }
        public System.DateTime CreationTime { get; set; }
        public System.DateTime LastUpdateTime { get; set; }
        public string CashCode { get; set; }
        public Nullable<long> Date { get; set; }
        public Nullable<int> ActivatedBonusType { get; set; }
        public Nullable<decimal> CommissionAmount { get; set; }
        public string CardNumber { get; set; }
        public Nullable<int> SegmentId { get; set; }
        public string CountryCode { get; set; }
        public Nullable<int> DepositCount { get; set; }
        public Nullable<long> AccountId { get; set; }
        public Nullable<long> ParentId { get; set; }
    
        public virtual Account Account { get; set; }
        public virtual BetShop BetShop { get; set; }
        public virtual CashDesk CashDesk { get; set; }
        public virtual Client Client { get; set; }
        public virtual Currency Currency { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<JobTrigger> JobTriggers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PaymentRequest> PaymentRequest1 { get; set; }
        public virtual PaymentRequest PaymentRequest2 { get; set; }
        public virtual User User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PaymentRequestHistory> PaymentRequestHistories { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PaymentRequestTransfer> PaymentRequestTransfers { get; set; }
        public virtual PartnerPaymentSetting PartnerPaymentSetting { get; set; }
        public virtual PaymentSystem PaymentSystem { get; set; }
    }
}
