//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IqSoft.CP.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Product()
        {
            this.AffiliateCommissions = new HashSet<AffiliateCommission>();
            this.AgentCommissions = new HashSet<AgentCommission>();
            this.BetShopTickets = new HashSet<BetShopTicket>();
            this.BonusProducts = new HashSet<BonusProduct>();
            this.ClientClassifications = new HashSet<ClientClassification>();
            this.ClientFavoriteProducts = new HashSet<ClientFavoriteProduct>();
            this.ClientSessions = new HashSet<ClientSession>();
            this.ComplimentaryPointRates = new HashSet<ComplimentaryPointRate>();
            this.Documents = new HashSet<Document>();
            this.JackpotSettings = new HashSet<JackpotSetting>();
            this.PartnerProductSettings = new HashSet<PartnerProductSetting>();
            this.Product1 = new HashSet<Product>();
            this.ProductCountrySettings = new HashSet<ProductCountrySetting>();
            this.ProductLimits = new HashSet<ProductLimit>();
            this.TriggerProductSettings = new HashSet<TriggerProductSetting>();
            this.AgentProfits = new HashSet<AgentProfit>();
        }
    
        public int Id { get; set; }
        public long TranslationId { get; set; }
        public Nullable<int> GameProviderId { get; set; }
        public Nullable<int> PaymentSystemId { get; set; }
        public int Level { get; set; }
        public string NickName { get; set; }
        public Nullable<int> ParentId { get; set; }
        public string ExternalId { get; set; }
        public int State { get; set; }
        public bool IsForDesktop { get; set; }
        public bool IsForMobile { get; set; }
        public string WebImageUrl { get; set; }
        public string MobileImageUrl { get; set; }
        public Nullable<int> SubproviderId { get; set; }
        public bool HasDemo { get; set; }
        public Nullable<int> CategoryId { get; set; }
        public string Jackpot { get; set; }
        public Nullable<bool> FreeSpinSupport { get; set; }
        public string BackgroundImageUrl { get; set; }
        public Nullable<decimal> RTP { get; set; }
        public System.DateTime CreationTime { get; set; }
        public System.DateTime LastUpdateTime { get; set; }
        public string Lines { get; set; }
        public string BetValues { get; set; }
        public string Path { get; set; }
        public string Volatility { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AffiliateCommission> AffiliateCommissions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AgentCommission> AgentCommissions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BetShopTicket> BetShopTickets { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BonusProduct> BonusProducts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ClientClassification> ClientClassifications { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ClientFavoriteProduct> ClientFavoriteProducts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ClientSession> ClientSessions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ComplimentaryPointRate> ComplimentaryPointRates { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Document> Documents { get; set; }
        public virtual GameProvider GameProvider { get; set; }
        public virtual GameProvider GameProvider1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<JackpotSetting> JackpotSettings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PartnerProductSetting> PartnerProductSettings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Product> Product1 { get; set; }
        public virtual Product Product2 { get; set; }
        public virtual ProductCategory ProductCategory { get; set; }
        public virtual Translation Translation { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductCountrySetting> ProductCountrySettings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductLimit> ProductLimits { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TriggerProductSetting> TriggerProductSettings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AgentProfit> AgentProfits { get; set; }
    }
}
