//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IqSoft.CP.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Region
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Region()
        {
            this.ProductCountrySettings = new HashSet<ProductCountrySetting>();
            this.BonusCountrySettings = new HashSet<BonusCountrySetting>();
            this.PartnerCountrySettings = new HashSet<PartnerCountrySetting>();
            this.PartnerPaymentCountrySettings = new HashSet<PartnerPaymentCountrySetting>();
            this.Region1 = new HashSet<Region>();
            this.Clients = new HashSet<Client>();
            this.Clients1 = new HashSet<Client>();
        }
    
        public int Id { get; set; }
        public Nullable<int> ParentId { get; set; }
        public int TypeId { get; set; }
        public string NickName { get; set; }
        public string IsoCode { get; set; }
        public long TranslationId { get; set; }
        public string Path { get; set; }
        public int State { get; set; }
        public string CurrencyId { get; set; }
        public string LanguageId { get; set; }
        public string Info { get; set; }
        public string IsoCode3 { get; set; }
    
        public virtual Language Language { get; set; }
        public virtual Currency Currency { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductCountrySetting> ProductCountrySettings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BonusCountrySetting> BonusCountrySettings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PartnerCountrySetting> PartnerCountrySettings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PartnerPaymentCountrySetting> PartnerPaymentCountrySettings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Region> Region1 { get; set; }
        public virtual Region Region2 { get; set; }
        public virtual Translation Translation { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Client> Clients { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Client> Clients1 { get; set; }
    }
}
