//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IqSoft.CP.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class SegmentSetting
    {
        public int Id { get; set; }
        public int SegmentId { get; set; }
        public string Name { get; set; }
        public string StringValue { get; set; }
        public Nullable<decimal> NumericValue { get; set; }
        public Nullable<System.DateTime> DateValue { get; set; }
        public Nullable<System.DateTime> CreationTime { get; set; }
        public System.DateTime LastUpdateTime { get; set; }
    
        public virtual Segment Segment { get; set; }
    }
}
