//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IqSoft.CP.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Segment
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Segment()
        {
            this.BannerSegmentSettings = new HashSet<BannerSegmentSetting>();
            this.BonusSegmentSettings = new HashSet<BonusSegmentSetting>();
            this.ClientClassifications = new HashSet<ClientClassification>();
            this.PromotionSegmentSettings = new HashSet<PromotionSegmentSetting>();
            this.SegmentSettings = new HashSet<SegmentSetting>();
            this.TriggerSettings = new HashSet<TriggerSetting>();
            this.JobTriggers = new HashSet<JobTrigger>();
            this.NewsSegmentSettings = new HashSet<NewsSegmentSetting>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public int PartnerId { get; set; }
        public int State { get; set; }
        public int Mode { get; set; }
        public System.DateTime CreationTime { get; set; }
        public System.DateTime LastUpdateTime { get; set; }
        public Nullable<int> Gender { get; set; }
        public Nullable<bool> IsKYCVerified { get; set; }
        public Nullable<bool> IsTermsConditionAccepted { get; set; }
        public string ClientStatus { get; set; }
        public string ClientId { get; set; }
        public string Email { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Region { get; set; }
        public string AffiliateId { get; set; }
        public string MobileCode { get; set; }
        public string SessionPeriod { get; set; }
        public string SignUpPeriod { get; set; }
        public string SegmentId { get; set; }
        public string TotalDepositsCount { get; set; }
        public string TotalDepositsAmount { get; set; }
        public string TotalWithdrawalsCount { get; set; }
        public string TotalWithdrawalsAmount { get; set; }
        public string TotalBetsCount { get; set; }
        public string Profit { get; set; }
        public string Bonus { get; set; }
        public string SuccessDepositPaymentSystem { get; set; }
        public string SuccessWithdrawalPaymentSystem { get; set; }
        public string ComplimentaryPoint { get; set; }
        public string CasinoBetsCount { get; set; }
        public string SportBetsCount { get; set; }
        public string TotalBetsAmount { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BannerSegmentSetting> BannerSegmentSettings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BonusSegmentSetting> BonusSegmentSettings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ClientClassification> ClientClassifications { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PromotionSegmentSetting> PromotionSegmentSettings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SegmentSetting> SegmentSettings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TriggerSetting> TriggerSettings { get; set; }
        public virtual Partner Partner { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<JobTrigger> JobTriggers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NewsSegmentSetting> NewsSegmentSettings { get; set; }
    }
}
