//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IqSoft.CP.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TicketMessageState
    {
        public long Id { get; set; }
        public Nullable<int> ClientId { get; set; }
        public long MessageId { get; set; }
        public System.DateTime CreationTime { get; set; }
        public Nullable<int> UserId { get; set; }
    
        public virtual TicketMessage TicketMessage { get; set; }
        public virtual User User { get; set; }
        public virtual Client Client { get; set; }
    }
}
