//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IqSoft.CP.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TranslationEntry
    {
        public long Id { get; set; }
        public long TranslationId { get; set; }
        public string LanguageId { get; set; }
        public string Text { get; set; }
        public Nullable<long> SessionId { get; set; }
        public System.DateTime CreationTime { get; set; }
        public System.DateTime LastUpdateTime { get; set; }
    
        public virtual Language Language { get; set; }
        public virtual Translation Translation { get; set; }
        public virtual UserSession UserSession { get; set; }
    }
}
