//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IqSoft.CP.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TriggerSetting
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TriggerSetting()
        {
            this.AmountCurrencySettings = new HashSet<AmountCurrencySetting>();
            this.BonusPaymentSystemSettings = new HashSet<BonusPaymentSystemSetting>();
            this.ClientBonusTriggers = new HashSet<ClientBonusTrigger>();
            this.TriggerGroupSettings = new HashSet<TriggerGroupSetting>();
            this.TriggerProductSettings = new HashSet<TriggerProductSetting>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public long TranslationId { get; set; }
        public int Type { get; set; }
        public System.DateTime StartTime { get; set; }
        public System.DateTime FinishTime { get; set; }
        public int Percent { get; set; }
        public string BonusSettingCodes { get; set; }
        public int PartnerId { get; set; }
        public System.DateTime CreationTime { get; set; }
        public System.DateTime LastUpdateTime { get; set; }
        public Nullable<decimal> MinAmount { get; set; }
        public Nullable<decimal> MaxAmount { get; set; }
        public string Condition { get; set; }
        public Nullable<int> MinBetCount { get; set; }
        public Nullable<int> SegmentId { get; set; }
        public Nullable<int> DayOfWeek { get; set; }
        public Nullable<decimal> UpToAmount { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<bool> ConsiderBonusBets { get; set; }
        public Nullable<decimal> Amount { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AmountCurrencySetting> AmountCurrencySettings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BonusPaymentSystemSetting> BonusPaymentSystemSettings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ClientBonusTrigger> ClientBonusTriggers { get; set; }
        public virtual Partner Partner { get; set; }
        public virtual Translation Translation { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TriggerGroupSetting> TriggerGroupSettings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TriggerProductSetting> TriggerProductSettings { get; set; }
        public virtual Segment Segment { get; set; }
    }
}
