//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IqSoft.CP.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TriggerProductSetting
    {
        public int Id { get; set; }
        public int TriggerSettingId { get; set; }
        public int ProductId { get; set; }
        public decimal Percent { get; set; }
    
        public virtual Product Product { get; set; }
        public virtual TriggerSetting TriggerSetting { get; set; }
    }
}
