//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IqSoft.CP.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class WebSiteMenu
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public WebSiteMenu()
        {
            this.WebSiteMenuItems = new HashSet<WebSiteMenuItem>();
        }
    
        public int Id { get; set; }
        public int PartnerId { get; set; }
        public string Type { get; set; }
        public string StyleType { get; set; }
        public Nullable<int> DeviceType { get; set; }
    
        public virtual Partner Partner { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WebSiteMenuItem> WebSiteMenuItems { get; set; }
    }
}
