// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace IqSoft.CP.DAL
{
    public partial class AccountBalance
    {
        public long Id { get; set; }
        public long AccountId { get; set; }
        public decimal Balance { get; set; }
        public DateTime Date { get; set; }

        public virtual Account Account { get; set; }
    }
}