// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace IqSoft.CP.DAL
{
    public partial class AffiliatePlatform
    {
        public AffiliatePlatform()
        {
            AffiliateReferrals = new HashSet<AffiliateReferral>();
        }

        public int Id { get; set; }
        public int PartnerId { get; set; }
        public string Name { get; set; }
        public int Status { get; set; }
        public Nullable<System.DateTime> KickOffTime { get; set; }
        public Nullable<System.DateTime> LastExecutionTime { get; set; }
        public Nullable<int> StepInHours { get; set; }
        public Nullable<int> PeriodInHours { get; set; }

        public virtual Partner Partner { get; set; }
        public virtual ICollection<AffiliateReferral> AffiliateReferrals { get; set; }
    }
}