// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace IqSoft.CP.DAL
{
    public partial class BannerSegmentSetting
    {
        public int Id { get; set; }
        public int BannerId { get; set; }
        public int SegmentId { get; set; }
        public int Type { get; set; }

        public virtual Banner Banner { get; set; }
        public virtual Segment Segment { get; set; }
    }
}