// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace IqSoft.CP.DAL
{
    public partial class Bet
    {
        public long Id { get; set; }
        public long BetDocumentId { get; set; }
        public long? WinDocumentId { get; set; }
        public long? PayDocumentId { get; set; }
        public string CurrencyId { get; set; }
        public int ProductId { get; set; }
        public decimal BetAmount { get; set; }
        public decimal WinAmount { get; set; }
        public int State { get; set; }
        public int TypeId { get; set; }
        public int? CashDeskId { get; set; }
        public int? ClientId { get; set; }
        public long? TicketNumber { get; set; }
        public int? UserId { get; set; }
        public int DeviceTypeId { get; set; }
        public DateTime BetTime { get; set; }
        public DateTime? CalculationTime { get; set; }
        public DateTime? PayTime { get; set; }
        public long BetDate { get; set; }
        public long? CalculationDate { get; set; }
        public long? PayDate { get; set; }
        public long? JackpotDocumentId { get; set; }
        public long? BonusDocumentId { get; set; }
        public int? BonusId { get; set; }
        public int? SelectionsCount { get; set; }
        public decimal? Coefficient { get; set; }
        public DateTime? LastUpdateTime { get; set; }
        public decimal? Rake { get; set; }
        public Nullable<decimal> BonusAmount { get; set; }

        public virtual CashDesk CashDesk { get; set; }
        public virtual Client Client { get; set; }
        public virtual Currency Currency { get; set; }
        public virtual Product Product { get; set; }
        public virtual User User { get; set; }
    }
}