// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace IqSoft.CP.DAL
{
    public partial class BetShopReconing
    {
        public long Id { get; set; }
        public int BetShopId { get; set; }
        public int UserId { get; set; }
        public decimal Amount { get; set; }
        public decimal BetShopAvailiableBalance { get; set; }
        public long DocumentId { get; set; }
        public string CurrencyId { get; set; }
        public DateTime CreationTime { get; set; }

        public virtual BetShop BetShop { get; set; }
        public virtual Currency Currency { get; set; }
        public virtual User User { get; set; }
    }
}