// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace IqSoft.CP.DAL
{
    public partial class BetShopGroup
    {
        public BetShopGroup()
        {
            BetShops = new HashSet<BetShop>();
            InverseParent = new HashSet<BetShopGroup>();
        }

        public int Id { get; set; }
        public int? ParentId { get; set; }
        public int PartnerId { get; set; }
        public string Path { get; set; }
        public string Name { get; set; }
        public int State { get; set; }
        public bool IsLeaf { get; set; }
        public long SessionId { get; set; }
        public DateTime CreationTime { get; set; }
        public DateTime LastUpdateTime { get; set; }

        public virtual BetShopGroup Parent { get; set; }
        public virtual Partner Partner { get; set; }
        public virtual UserSession Session { get; set; }
        public virtual ICollection<BetShop> BetShops { get; set; }
        public virtual ICollection<BetShopGroup> InverseParent { get; set; }
    }
}