// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace IqSoft.CP.DAL
{
    public partial class BonusPaymentSystemSetting
    {
        public int Id { get; set; }
        public int PaymentSystemId { get; set; }
        public int? BonusId { get; set; }
        public int? TriggerId { get; set; }
        public int Type { get; set; }

        public virtual Bonu Bonus { get; set; }
        public virtual PaymentSystem PaymentSystem { get; set; }
        public virtual TriggerSetting Trigger { get; set; }
    }
}