// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace IqSoft.CP.DAL
{
    public partial class BonusProduct
    {
        public int Id { get; set; }
        public int BonusId { get; set; }
        public int ProductId { get; set; }
        public decimal CashBackPercent { get; set; }

        public virtual Bonu Bonus { get; set; }
        public virtual Product Product { get; set; }
    }
}