// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace IqSoft.CP.DAL
{
    public partial class CashDesk
    {
        public CashDesk()
        {
            Bets = new HashSet<Bet>();
            CashDeskShifts = new HashSet<CashDeskShift>();
            Documents = new HashSet<Document>();
            PaymentRequests = new HashSet<PaymentRequest>();
            UserSessions = new HashSet<UserSession>();
        }

        public int Id { get; set; }
        public int BetShopId { get; set; }
        public string Name { get; set; }
        public int State { get; set; }
        public string MacAddress { get; set; }
        public string EncryptPassword { get; set; }
        public string EncryptSalt { get; set; }
        public string EncryptIv { get; set; }
        public long SessionId { get; set; }
        public DateTime CreationTime { get; set; }
        public DateTime LastUpdateTime { get; set; }
        public int CurrentCashierId { get; set; }
        public int? CurrentShiftNumber { get; set; }
        public int Type { get; set; }

        public virtual BetShop BetShop { get; set; }
        public virtual User CurrentCashier { get; set; }
        public virtual UserSession Session { get; set; }
        public virtual ICollection<Bet> Bets { get; set; }
        public virtual ICollection<CashDeskShift> CashDeskShifts { get; set; }
        public virtual ICollection<Document> Documents { get; set; }
        public virtual ICollection<PaymentRequest> PaymentRequests { get; set; }
        public virtual ICollection<UserSession> UserSessions { get; set; }
    }
}