// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace IqSoft.CP.DAL
{
    public partial class ClientSecurityAnswer
    {
        public int Id { get; set; }
        public int ClientId { get; set; }
        public int SecurityQuestionId { get; set; }
        public string Answer { get; set; }

        public virtual Client Client { get; set; }
        public virtual SecurityQuestion SecurityQuestion { get; set; }
    }
}