// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace IqSoft.CP.DAL
{
    public partial class ClientInfo
    {
        public long Id { get; set; }
        public int? PartnerId { get; set; }
        public int? ClientId { get; set; }
        public int Type { get; set; }
        public string Data { get; set; }
        public DateTime CreationTime { get; set; }
        public int State { get; set; }
        public string MobileOrEmail { get; set; }
        public string Ip { get; set; }

        public virtual Client Client { get; set; }
        public virtual Partner Partner { get; set; }
    }
}