// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace IqSoft.CP.DAL
{
    public partial class ClientBonusTrigger
    {
        public int Id { get; set; }
        public int? ClientId { get; set; }
        public int TriggerId { get; set; }
        public int BonusId { get; set; }
        public decimal? SourceAmount { get; set; }
        public DateTime? CreationTime { get; set; }
        public int? BetCount { get; set; }
        public decimal? WageringAmount { get; set; }
        public int? ReuseNumber { get; set; }

        public virtual Bonu Bonus { get; set; }
        public virtual Client Client { get; set; }
        public virtual TriggerSetting Trigger { get; set; }
    }
}