// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace IqSoft.CP.DAL
{
    public partial class ClientIdentity
    {
        public int Id { get; set; }
        public int ClientId { get; set; }
        public int? UserId { get; set; }
        public int DocumentTypeId { get; set; }
        public string ImagePath { get; set; }
        public int Status { get; set; }
        public DateTime CreationTime { get; set; }
        public DateTime LastUpdateTime { get; set; }
        public DateTime? ExpirationTime { get; set; }
        public long? ExpirationDate { get; set; }

        public virtual Client Client { get; set; }
        public virtual User User { get; set; }
    }
}