// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace IqSoft.CP.DAL
{
    public partial class ClientMessage
    {
        public ClientMessage()
        {
            ClientMessageStates = new HashSet<ClientMessageState>();
        }

        public long Id { get; set; }
        public long? ParentId { get; set; }
        public int PartnerId { get; set; }
        public int? ClientId { get; set; }
        public string Subject { get; set; }
        public string Message { get; set; }
        public int Type { get; set; }
        public long? SessionId { get; set; }
        public DateTime CreationTime { get; set; }
        public int? EmailId { get; set; }
        public string MobileOrEmail { get; set; }

        public virtual Client Client { get; set; }
        public virtual Email Email { get; set; }
        public virtual UserSession Session { get; set; }
        public virtual ICollection<ClientMessageState> ClientMessageStates { get; set; }
    }
}