// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace IqSoft.CP.DAL
{
    public partial class Currency
    {
        public Currency()
        {
            Accounts = new HashSet<Account>();
            Bets = new HashSet<Bet>();
            BetShops = new HashSet<BetShop>();
            BetShopReconings = new HashSet<BetShopReconing>();
            BonusCurrencySettings = new HashSet<BonusCurrencySetting>();
            Clients = new HashSet<Client>();
            ComplimentaryPointRates = new HashSet<ComplimentaryPointRate>();
            ObjectCurrencyPriorities = new HashSet<ObjectCurrencyPriority>();
            PartnerBankInfoes = new HashSet<PartnerBankInfo>();
            PartnerCurrencySettings = new HashSet<PartnerCurrencySetting>();
            PartnerPaymentCurrencyRates = new HashSet<PartnerPaymentCurrencyRate>();
            PartnerPaymentSettings = new HashSet<PartnerPaymentSetting>();
            CurrencyRates = new HashSet<CurrencyRate>();
            Users = new HashSet<User>();
            Regions = new HashSet<Region>();
            Documents = new HashSet<Document>();
            PaymentRequests = new HashSet<PaymentRequest>();
            Partners = new HashSet<Partner>();
            Affiliates = new HashSet<Affiliate>();
        }

        public string Id { get; set; }
        public decimal CurrentRate { get; set; }
        public string Symbol { get; set; }
        public long SessionId { get; set; }
        public DateTime CreationTime { get; set; }
        public DateTime LastUpdateTime { get; set; }
        public string Code { get; set; }
        public string Name { get; set; }

        public virtual UserSession Session { get; set; }
        public virtual ICollection<Account> Accounts { get; set; }
        public virtual ICollection<BetShopReconing> BetShopReconings { get; set; }
        public virtual ICollection<BetShop> BetShops { get; set; }
        public virtual ICollection<Bet> Bets { get; set; }
        public virtual ICollection<BonusCurrencySetting> BonusCurrencySettings { get; set; }
        public virtual ICollection<Client> Clients { get; set; }
        public virtual ICollection<ComplimentaryPointRate> ComplimentaryPointRates { get; set; }
        public virtual ICollection<CurrencyRate> CurrencyRates { get; set; }
        public virtual ICollection<Document> Documents { get; set; }
        public virtual ICollection<ObjectCurrencyPriority> ObjectCurrencyPriorities { get; set; }
        public virtual ICollection<PartnerBankInfo> PartnerBankInfoes { get; set; }
        public virtual ICollection<PartnerCurrencySetting> PartnerCurrencySettings { get; set; }
        public virtual ICollection<PartnerPaymentCurrencyRate> PartnerPaymentCurrencyRates { get; set; }
        public virtual ICollection<PartnerPaymentSetting> PartnerPaymentSettings { get; set; }
        public virtual ICollection<Partner> Partners { get; set; }
        public virtual ICollection<PaymentRequest> PaymentRequests { get; set; }
        public virtual ICollection<Region> Regions { get; set; }
        public virtual ICollection<User> Users { get; set; }
        public virtual ICollection<Affiliate> Affiliates { get; set; }
    }
}