// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace IqSoft.CP.DAL
{
    public partial class CurrencyRate
    {
        public int Id { get; set; }
        public string CurrencyId { get; set; }
        public decimal RateBefore { get; set; }
        public decimal RateAfter { get; set; }
        public long SessionId { get; set; }
        public DateTime CreationTime { get; set; }
        public DateTime LastUpdateTime { get; set; }

        public virtual Currency Currency { get; set; }
        public virtual UserSession Session { get; set; }
    }
}