// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace IqSoft.CP.DAL
{
    public partial class Document
    {
        public Document()
        {
            InverseParent = new HashSet<Document>();
            Transactions = new HashSet<Transaction>();
        }

        public long Id { get; set; }
        public string ExternalTransactionId { get; set; }
        public decimal Amount { get; set; }
        public string CurrencyId { get; set; }
        public int State { get; set; }
        public int OperationTypeId { get; set; }
        public int? TypeId { get; set; }
        public long? ParentId { get; set; }
        public long? PaymentRequestId { get; set; }
        public string RoundId { get; set; }
        public string Info { get; set; }
        public int? Creator { get; set; }
        public int? CashDeskId { get; set; }
        public int? PartnerPaymentSettingId { get; set; }
        public int? PartnerProductId { get; set; }
        public int? GameProviderId { get; set; }
        public int? ClientId { get; set; }
        public long? ExternalOperationId { get; set; }
        public long? TicketNumber { get; set; }
        public string TicketInfo { get; set; }
        public int? UserId { get; set; }
        public int? DeviceTypeId { get; set; }
        public decimal? PossibleWin { get; set; }
        public long? SessionId { get; set; }
        public DateTime CreationTime { get; set; }
        public DateTime LastUpdateTime { get; set; }
        public int? ProductId { get; set; }
        public bool? HasNote { get; set; }
        public long? Date { get; set; }

        public virtual CashDesk CashDesk { get; set; }
        public virtual Client Client { get; set; }
        public virtual Currency Currency { get; set; }
        public virtual GameProvider GameProvider { get; set; }
        public virtual OperationType OperationType { get; set; }
        public virtual Document Parent { get; set; }
        public virtual PartnerPaymentSetting PartnerPaymentSetting { get; set; }
        public virtual Product Product { get; set; }
        public virtual ICollection<Document> InverseParent { get; set; }
        public virtual ICollection<Transaction> Transactions { get; set; }
    }
}