// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace IqSoft.CP.DAL
{
    public partial class Email
    {
        public Email()
        {
            ClientMessages = new HashSet<ClientMessage>();
        }

        public int Id { get; set; }
        public int PartnerId { get; set; }
        public string Receiver { get; set; }
        public int Status { get; set; }
        public string Subject { get; set; }
        public string Body { get; set; }
        public int? MessageTemplateId { get; set; }
        public DateTime? CreationTime { get; set; }

        public virtual MessageTemplate MessageTemplate { get; set; }
        public virtual Partner Partner { get; set; }
        public virtual ICollection<ClientMessage> ClientMessages { get; set; }
    }
}