// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace IqSoft.CP.DAL
{
    public partial class fnAccountType
    {
        public int Id { get; set; }
        public string NickName { get; set; }
        public int Kind { get; set; }
        public bool CanBeNegative { get; set; }
        public long TranslationId { get; set; }
        public string Name { get; set; }
    }
}
