// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace IqSoft.CP.DAL
{
    public partial class fnAffiliateClient
    {
        public string AffiliateManagerId { get; set; }
        public int ClientId { get; set; }
        public decimal? TotalBetAmount { get; set; }
        public decimal? TotalWinAmount { get; set; }
    }
}
