// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace IqSoft.CP.DAL
{
    public partial class fnBanner
    {
        public int Id { get; set; }
        public int PartnerId { get; set; }
        public int Type { get; set; }
        public string NickName { get; set; }
        public string Link { get; set; }
        public bool ShowDescription { get; set; }
        public int? ButtonType { get; set; }
        public int Order { get; set; }
        public bool IsEnabled { get; set; }
        public string Image { get; set; }
        public DateTime StartDate { get; set; }
        public string Visibility { get; set; }
        public DateTime EndDate { get; set; }
        public string Head { get; set; }
        public string Body { get; set; }
    }
}
