// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace IqSoft.CP.DAL
{
    public partial class fnBonus
    {
        public int Id { get; set; }
        public string NickName { get; set; }
        public string Description { get; set; }
        public int PartnerId { get; set; }
        public int? AccountTypeId { get; set; }
        public bool Status { get; set; }
        public DateTime StartTime { get; set; }
        public DateTime FinishTime { get; set; }
        public DateTime LastExecutionTime { get; set; }
        public int Period { get; set; }
        public int BonusType { get; set; }
        public string Info { get; set; }
        public int? TurnoverCount { get; set; }
        public decimal? MinAmount { get; set; }
        public decimal? MaxAmount { get; set; }
        public int? Sequence { get; set; }
        public long? TranslationId { get; set; }
        public int? Priority { get; set; }
        public bool? IgnoreEligibility { get; set; }
        public int? ValidForAwarding { get; set; }
        public int? ValidForSpending { get; set; }
        public int? ReusingMaxCount { get; set; }
        public bool? ResetOnWithdraw { get; set; }
        public DateTime? CreationTime { get; set; }
        public DateTime? LastUpdateTime { get; set; }
        public bool? AllowSplit { get; set; }
        public decimal? MaxGranted { get; set; }
        public decimal? TotalGranted { get; set; }
        public int? MaxReceiversCount { get; set; }
        public int? TotalReceiversCount { get; set; }
        public int? LinkedBonusId { get; set; }
        public decimal? AutoApproveMaxAmount { get; set; }
        public bool? RefundRollbacked { get; set; }
        public string Condition { get; set; }
        public string Name { get; set; }
    }
}
