// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace IqSoft.CP.DAL
{
    public partial class fnCashDesks
    {
        public int Id { get; set; }
        public int BetShopId { get; set; }
        public DateTime CreationTime { get; set; }
        public DateTime LastUpdateTime { get; set; }
        public string Name { get; set; }
        public int State { get; set; }
        public string EncryptIv { get; set; }
        public string EncryptSalt { get; set; }
        public string MacAddress { get; set; }
        public int Type { get; set; }
        public decimal Balance { get; set; }
    }
}
