// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace IqSoft.CP.DAL
{
    public partial class fnClientLog
    {
        public long Id { get; set; }
        public int Action { get; set; }
        public int ClientId { get; set; }
        public int? UserId { get; set; }
        public string Ip { get; set; }
        public string Page { get; set; }
        public DateTime CreationTime { get; set; }
        public long? ClientSessionId { get; set; }
        public string UserFirstName { get; set; }
        public string UserLastName { get; set; }
    }
}
