// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace IqSoft.CP.DAL
{
    public partial class fnClientInfoForDashboard
    {
        public string CurrencyId { get; set; }
        public decimal? MaxBet { get; set; }
        public decimal? MaxWin { get; set; }
        public decimal? TotalBetAmount { get; set; }
        public decimal? CashoutAmount { get; set; }
        public int? TotalBetCount { get; set; }
    }
}
