// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace IqSoft.CP.DAL
{
    public partial class fnClientReport
    {
        public int ClientId { get; set; }
        public string UserName { get; set; }
        public int PartnerId { get; set; }
        public string CurrencyId { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public int? AffiliatePlatformId { get; set; }
        public string AffiliateId { get; set; }
        public string AffiliateReferralId { get; set; }
        public decimal? TotalWithdrawalAmount { get; set; }
        public int? WithdrawalsCount { get; set; }
        public decimal? TotalDepositAmount { get; set; }
        public int? DepositsCount { get; set; }
        public decimal? TotalBetAmount { get; set; }
        public int? BetsCount { get; set; }
        public decimal? TotalWinAmount { get; set; }
        public int? WinsCount { get; set; }
        public decimal? GGR { get; set; }
        public decimal? TotalDebitCorrection { get; set; }
        public int? DebitCorrectionsCount { get; set; }
        public decimal? TotalCreditCorrection { get; set; }
        public int? CreditCorrectionsCount { get; set; }
    }
}
