// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace IqSoft.CP.DAL
{
    public partial class fnInternetBetByClient
    {
        public int? ClientId { get; set; }
        public string UserName { get; set; }
        public string Currency { get; set; }
        public int? TotalDepositsCount { get; set; }
        public decimal? TotalDepositsAmount { get; set; }
        public int? TotalWithdrawalsCount { get; set; }
        public decimal? TotalWithdrawalsAmount { get; set; }
        public decimal? Balance { get; set; }
    }
}
