// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace IqSoft.CP.DAL
{
    public partial class fnProfitByAgent
    {
        public int AgentId { get; set; }
        public string AgentPath { get; set; }
        public int ProductId { get; set; }
        public int? SelectionsCount { get; set; }
        public decimal? TotalBetAmount { get; set; }
        public decimal? TotalWinAmount { get; set; }
    }
}
