// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace IqSoft.CP.DAL
{
    public partial class fnProductCommission
    {
        public decimal? Percent { get; set; }
        public string TurnoverPercent { get; set; }
    }
}
