// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace IqSoft.CP.DAL
{
    public partial class fnReportByAgentTransfer
    {
        public int PartnerId { get; set; }
        public string PartnerName { get; set; }
        public int UserId { get; set; }
        public string UserName { get; set; }
        public string NickName { get; set; }
        public decimal? TotoalProfit { get; set; }
        public decimal? TotalDebit { get; set; }
        public decimal? Balance { get; set; }
    }
}
