// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace IqSoft.CP.DAL
{
    public partial class fnReportByProduct
    {
        public int ClientId { get; set; }
        public int PartnerId { get; set; }
        public string ClientFirstName { get; set; }
        public string ClientLastName { get; set; }
        public string Currency { get; set; }
        public int CategoryId { get; set; }
        public int ProductId { get; set; }
        public string ProductName { get; set; }
        public int? DeviceTypeId { get; set; }
        public string ProviderName { get; set; }
        public decimal? TotalBetsAmount { get; set; }
        public decimal? TotalWinsAmount { get; set; }
        public int? TotalBetsCount { get; set; }
        public int? TotalUncalculatedBetsCount { get; set; }
        public decimal? TotalUncalculatedBetsAmount { get; set; }
        public decimal? GGR { get; set; }
        public int? AffiliateReferralId { get; set; }
    }
}
