// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace IqSoft.CP.DAL
{
    public partial class fnRegion
    {
        public int Id { get; set; }
        public int? ParentId { get; set; }
        public int TypeId { get; set; }
        public string IsoCode { get; set; }
        public string IsoCode3 { get; set; }
        public int State { get; set; }
        public string CurrencyId { get; set; }
        public string Name { get; set; }
        public string LanguageId { get; set; }
        public string Info { get; set; }
        public string NickName { get; set; }
        public string Path { get; set; }
    }
}
