// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace IqSoft.CP.DAL
{
    public partial class fnReportByPartner
    {
        public int PartnerId { get; set; }
        public string PartnerName { get; set; }
        public decimal? TotalBetAmount { get; set; }
        public int? TotalBetsCount { get; set; }
        public decimal? TotalWinAmount { get; set; }
        public decimal? TotalGGR { get; set; }
    }
}
