// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace IqSoft.CP.DAL
{
    public partial class fnShiftReport
    {
        public decimal BetAmount { get; set; }
        public decimal WinAmount { get; set; }
        public decimal CalculatedBetAmount { get; set; }
        public decimal PayedWin { get; set; }
        public decimal DepositToInternetClient { get; set; }
        public decimal WithdrawFromInternetClient { get; set; }
        public decimal DebitCorrectionOnCashDesk { get; set; }
        public decimal CreditCorrectionOnCashDesk { get; set; }
    }
}
