// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace IqSoft.CP.DAL
{
    public partial class fnTicket
    {
        public long Id { get; set; }
        public int? ClientId { get; set; }
        public string UserName { get; set; }
        public int PartnerId { get; set; }
        public string Subject { get; set; }
        public int Status { get; set; }
        public int Type { get; set; }
        public int? UserUnreadMessagesCount { get; set; }
        public DateTime CreationTime { get; set; }
        public long LastMessageDate { get; set; }
        public DateTime LastMessageTime { get; set; }
        public int? AffiliateReferralId { get; set; }
        public int? UserId { get; set; }
        public string UserFirstName { get; set; }
        public string UserLastName { get; set; }
        public string ClientPath { get; set; }
    }
}
