// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace IqSoft.CP.DAL
{
    public partial class fnTransaction
    {
        public long Id { get; set; }
        public long DocumentId { get; set; }
        public long AccountId { get; set; }
        public decimal Amount { get; set; }
        public int OperationTypeId { get; set; }
        public int Type { get; set; }
        public DateTime CreationTime { get; set; }
        public long? Date { get; set; }
        public int? CashDeskId { get; set; }
        public int? Creator { get; set; }
        public string ExternalTransactionId { get; set; }
        public string Info { get; set; }
        public long? DocumentParentId { get; set; }
        public int? PartnerPaymentSettingId { get; set; }
        public string CurrencyId { get; set; }
        public long? PaymentRequestId { get; set; }
        public int DocumentState { get; set; }
        public long ObjectId { get; set; }
        public int ObjectTypeId { get; set; }
        public int AccountTypeId { get; set; }
        public string AccountCurrencyId { get; set; }
        public int? ClientId { get; set; }
        public int? UserId { get; set; }
        public long? ExternalOperationId { get; set; }
        public int? GameProviderId { get; set; }
        public string OperationTypeName { get; set; }
        public string PaymentSystemName { get; set; }
        public string ProductName { get; set; }
        public string GameProviderName { get; set; }
    }
}
