// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace IqSoft.CP.DAL
{
    public partial class fnUserCorrection
    {
        public long Id { get; set; }
        public decimal Amount { get; set; }
        public string CurrencyId { get; set; }
        public int State { get; set; }
        public string Info { get; set; }
        public int? ClientId { get; set; }
        public int? UserId { get; set; }
        public int? Creator { get; set; }
        public DateTime CreationTime { get; set; }
        public DateTime LastUpdateTime { get; set; }
        public bool? HasNote { get; set; }
        public long? Date { get; set; }
        public string OperationTypeName { get; set; }
        public string CreatorFirstName { get; set; }
        public string CreatorLastName { get; set; }
        public string UserFirstName { get; set; }
        public string UserLastName { get; set; }
        public string ClientFirstName { get; set; }
        public string ClientLastName { get; set; }
        public int? PartnerId { get; set; }
        public int? AffiliateReferralId { get; set; }
        public int? DocumentTypeId { get; set; }
        public int? ProductId { get; set; }
        public string ProductNickName { get; set; }
    }
}
