// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace IqSoft.CP.DAL
{
    public partial class fnUserLog
    {
        public long Id { get; set; }
        public int UserId { get; set; }
        public string Ip { get; set; }
        public string RequestMethod { get; set; }
        public string Page { get; set; }
        public DateTime CreationTime { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public int PartnerId { get; set; }
        public string Info { get; set; }
    }
}
