// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace IqSoft.CP.DAL
{
    public partial class JackpotSetting
    {
        public int Id { get; set; }
        public int ProductId { get; set; }
        public int JackpotId { get; set; }
        public decimal Percent { get; set; }
        public DateTime CreationDate { get; set; }
        public DateTime LastUpdateDate { get; set; }

        public virtual Jackpot Jackpot { get; set; }
        public virtual Product Product { get; set; }
    }
}