// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace IqSoft.CP.DAL
{
    public partial class JobResult
    {
        public long Id { get; set; }
        public int JobId { get; set; }
        public DateTime ExecutionTime { get; set; }
        public int Duration { get; set; }
        public string Message { get; set; }

        public virtual Job Job { get; set; }
    }
}