// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace IqSoft.CP.DAL
{
    public partial class JobTrigger
    {
        public long Id { get; set; }
        public int ClientId { get; set; }
        public int Type { get; set; }
        public int? SegmentId { get; set; }
        public int? JackpotId { get; set; }
        public decimal? Amount { get; set; }

        public virtual Client Client { get; set; }
        public virtual Jackpot Jackpot { get; set; }
        public virtual Segment Segment { get; set; }
    }
}