// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace IqSoft.CP.DAL
{
    public partial class LimitType
    {
        public LimitType()
        {
            ProductLimits = new HashSet<ProductLimit>();
        }

        public int Id { get; set; }
        public string Name { get; set; }

        public virtual ICollection<ProductLimit> ProductLimits { get; set; }
    }
}