// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace IqSoft.CP.DAL
{
    public partial class MessageTemplate
    {
        public MessageTemplate()
        {
            Emails = new HashSet<Email>();
        }

        public int Id { get; set; }
        public int PartnerId { get; set; }
        public string NickName { get; set; }
        public long TranslationId { get; set; }
        public int ClientInfoType { get; set; }
        public string ExternalTemplateId { get; set; }

        public virtual Partner Partner { get; set; }
        public virtual Translation Translation { get; set; }
        public virtual ICollection<Email> Emails { get; set; }
    }
}