// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace IqSoft.CP.DAL
{
    public partial class Note
    {
        public long Id { get; set; }
        public int ObjectTypeId { get; set; }
        public long ObjectId { get; set; }
        public string Message { get; set; }
        public int Type { get; set; }
        public int State { get; set; }
        public long SessionId { get; set; }
        public DateTime CreationTime { get; set; }
        public DateTime LastUpdateTime { get; set; }

        public virtual UserSession Session { get; set; }
    }
}