// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace IqSoft.CP.DAL
{
    public partial class ObjectChangeHistory
    {
        public long Id { get; set; }
        public long ObjectId { get; set; }
        public int ObjectTypeId { get; set; }
        public string Object { get; set; }
        public long? SessionId { get; set; }
        public DateTime ChangeDate { get; set; }
        public string Comment { get; set; }

        public virtual ObjectType ObjectType { get; set; }
        public virtual UserSession Session { get; set; }
    }
}