// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace IqSoft.CP.DAL
{
    public partial class ObjectType
    {
        public ObjectType()
        {
            Accounts = new HashSet<Account>();
            Announcements = new HashSet<Announcement>();
            Categories = new HashSet<Category>();
            GameProviderSettings = new HashSet<GameProviderSetting>();
            ObjectActions = new HashSet<ObjectAction>();
            ObjectChangeHistories = new HashSet<ObjectChangeHistory>();
            ObjectCurrencyPriorities = new HashSet<ObjectCurrencyPriority>();
            ObjectDataChangeHistories = new HashSet<ObjectDataChangeHistory>();
            ProductLimits = new HashSet<ProductLimit>();
        }

        public int Id { get; set; }
        public string Name { get; set; }
        public bool SaveChangeHistory { get; set; }
        public bool HasTranslation { get; set; }

        public virtual ICollection<Account> Accounts { get; set; }
        public virtual ICollection<Announcement> Announcements { get; set; }
        public virtual ICollection<Category> Categories { get; set; }
        public virtual ICollection<GameProviderSetting> GameProviderSettings { get; set; }
        public virtual ICollection<ObjectAction> ObjectActions { get; set; }
        public virtual ICollection<ObjectChangeHistory> ObjectChangeHistories { get; set; }
        public virtual ICollection<ObjectCurrencyPriority> ObjectCurrencyPriorities { get; set; }
        public virtual ICollection<ObjectDataChangeHistory> ObjectDataChangeHistories { get; set; }
        public virtual ICollection<ProductLimit> ProductLimits { get; set; }
    }
}