// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace IqSoft.CP.DAL
{
    public partial class ObjectDataChangeHistory
    {
        public long Id { get; set; }
        public int UserId { get; set; }
        public long ObjectId { get; set; }
        public int ObjectTypeId { get; set; }
        public string FieldName { get; set; }
        public string StringValue { get; set; }
        public decimal? NumericValue { get; set; }
        public DateTime CreationTime { get; set; }

        public virtual ObjectType ObjectType { get; set; }
        public virtual User User { get; set; }
    }
}