// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace IqSoft.CP.DAL
{
    public partial class PartnerProductSetting
    {
        public int Id { get; set; }
        public int PartnerId { get; set; }
        public int ProductId { get; set; }
        public decimal Percent { get; set; }
        public int State { get; set; }
        public decimal? Rating { get; set; }
        public int? CategoryId { get; set; }
        public int? OpenMode { get; set; }
        public bool? HasDemo { get; set; }
        public decimal? RTP { get; set; }
        public int? Volatility { get; set; }
        public System.DateTime CreationTime { get; set; }
        public System.DateTime LastUpdateTime { get; set; }

        public virtual Partner Partner { get; set; }
        public virtual Product Product { get; set; }
    }
}