// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace IqSoft.CP.DAL
{
    public partial class PartnerPaymentSetting
    {
        public PartnerPaymentSetting()
        {
            ClientPaymentInfoes = new HashSet<ClientPaymentInfo>();
            ClientPaymentSettings = new HashSet<ClientPaymentSetting>();
            Documents = new HashSet<Document>();
            PartnerPaymentCountrySettings = new HashSet<PartnerPaymentCountrySetting>();
            PartnerPaymentCurrencyRates = new HashSet<PartnerPaymentCurrencyRate>();
            PaymentRequests = new HashSet<PaymentRequest>();
        }

        public int Id { get; set; }
        public int PartnerId { get; set; }
        public int PaymentSystemId { get; set; }
        public decimal Commission { get; set; }
        public decimal FixedFee { get; set; }
        public int State { get; set; }
        public string CurrencyId { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public long SessionId { get; set; }
        public DateTime CreationTime { get; set; }
        public DateTime LastUpdateTime { get; set; }
        public int PaymentSystemPriority { get; set; }
        public int Type { get; set; }
        public string Info { get; set; }
        public string OSTypes { get; set; }
        public decimal MinAmount { get; set; }
        public decimal MaxAmount { get; set; }
        public bool? AllowMultipleClientsPerPaymentInfo { get; set; }
        public bool? AllowMultiplePaymentInfoes { get; set; }
        public int? OpenMode { get; set; }

        public virtual Currency Currency { get; set; }
        public virtual Partner Partner { get; set; }
        public virtual PaymentSystem PaymentSystem { get; set; }
        public virtual UserSession Session { get; set; }
        public virtual ICollection<ClientPaymentInfo> ClientPaymentInfoes { get; set; }
        public virtual ICollection<ClientPaymentSetting> ClientPaymentSettings { get; set; }
        public virtual ICollection<Document> Documents { get; set; }
        public virtual ICollection<PartnerPaymentCountrySetting> PartnerPaymentCountrySettings { get; set; }
        public virtual ICollection<PartnerPaymentCurrencyRate> PartnerPaymentCurrencyRates { get; set; }
        public virtual ICollection<PaymentRequest> PaymentRequests { get; set; }
    }
}