// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace IqSoft.CP.DAL
{
    public partial class PaymentSystem
    {
        public PaymentSystem()
        {
            BonusPaymentSystemSettings = new HashSet<BonusPaymentSystemSetting>();
            PartnerBankInfoes = new HashSet<PartnerBankInfo>();
            PartnerKeys = new HashSet<PartnerKey>();
            PartnerPaymentSettings = new HashSet<PartnerPaymentSetting>();
            PaymentRequestTransfers = new HashSet<PaymentRequestTransfer>();
            PaymentRequests = new HashSet<PaymentRequest>();
        }

        public int Id { get; set; }
        public string Name { get; set; }
        public int Type { get; set; }
        public long SessionId { get; set; }
        public DateTime CreationTime { get; set; }
        public DateTime LastUpdateTime { get; set; }
        public int PeriodicityOfRequest { get; set; }
        public int PaymentRequestSendCount { get; set; }
        public long TranslationId { get; set; }
        public int ContentType { get; set; }

        public virtual Translation Translation { get; set; }
        public virtual ICollection<BonusPaymentSystemSetting> BonusPaymentSystemSettings { get; set; }
        public virtual ICollection<PartnerBankInfo> PartnerBankInfoes { get; set; }
        public virtual ICollection<PartnerKey> PartnerKeys { get; set; }
        public virtual ICollection<PartnerPaymentSetting> PartnerPaymentSettings { get; set; }
        public virtual ICollection<PaymentRequestTransfer> PaymentRequestTransfers { get; set; }
        public virtual ICollection<PaymentRequest> PaymentRequests { get; set; }
    }
}