// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace IqSoft.CP.DAL
{
    public partial class PaymentRequestTransfer
    {
        public long Id { get; set; }
        public int PaymentSystemId { get; set; }
        public long PaymentRequestId { get; set; }
        public int State { get; set; }
        public DateTime LastSendDate { get; set; }
        public string Response { get; set; }
        public int RetryCount { get; set; }

        public virtual PaymentRequest PaymentRequest { get; set; }
        public virtual PaymentSystem PaymentSystem { get; set; }
    }
}