// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace IqSoft.CP.DAL
{
    public partial class PaymentRequestHistory
    {
        public long Id { get; set; }
        public long RequestId { get; set; }
        public int Status { get; set; }
        public string Comment { get; set; }
        public long? SessionId { get; set; }
        public DateTime CreationTime { get; set; }

        public virtual PaymentRequest Request { get; set; }
        public virtual UserSession Session { get; set; }
    }
}