// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace IqSoft.CP.DAL
{
    public partial class PaymentLimit
    {
        public int Id { get; set; }
        public int ClientId { get; set; }
        public int? MaxDepositsCountPerDay { get; set; }
        public decimal? MaxDepositAmount { get; set; }
        public decimal? MaxTotalDepositsAmountPerDay { get; set; }
        public decimal? MaxTotalDepositsAmountPerWeek { get; set; }
        public decimal? MaxTotalDepositsAmountPerMonth { get; set; }
        public decimal? MaxWithdrawAmount { get; set; }
        public decimal? MaxTotalWithdrawsAmountPerDay { get; set; }
        public decimal? MaxTotalWithdrawsAmountPerWeek { get; set; }
        public decimal? MaxTotalWithdrawsAmountPerMonth { get; set; }
        public DateTime? StartTime { get; set; }
        public DateTime? EndTime { get; set; }
        public int? LimitTypeId { get; set; }
        public int? RowState { get; set; }

        public virtual Client Client { get; set; }
    }
}