// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace IqSoft.CP.DAL
{
    public partial class Permission
    {
        public Permission()
        {
            AccessObjects = new HashSet<AccessObject>();
            RolePermissions = new HashSet<RolePermission>();
        }

        public string Id { get; set; }
        public string Name { get; set; }
        public int PermissionGroupId { get; set; }
        public int ObjectTypeId { get; set; }

        public virtual PermissionGroup PermissionGroup { get; set; }
        public virtual ICollection<AccessObject> AccessObjects { get; set; }
        public virtual ICollection<RolePermission> RolePermissions { get; set; }
    }
}