// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace IqSoft.CP.DAL
{
    public partial class Product
    {
        public Product()
        {
            AgentCommissions = new HashSet<AgentCommission>();
            AgentProfitProductGroups = new HashSet<AgentProfit>();
            AgentProfitProducts = new HashSet<AgentProfit>();
            BetShopTickets = new HashSet<BetShopTicket>();
            Bets = new HashSet<Bet>();
            BonusProducts = new HashSet<BonusProduct>();
            ClientClassifications = new HashSet<ClientClassification>();
            ClientFavoriteProducts = new HashSet<ClientFavoriteProduct>();
            ClientSessions = new HashSet<ClientSession>();
            ComplimentaryPointRates = new HashSet<ComplimentaryPointRate>();
            Documents = new HashSet<Document>();
            InverseParent = new HashSet<Product>();
            JackpotSettings = new HashSet<JackpotSetting>();
            PartnerProductSettings = new HashSet<PartnerProductSetting>();
            ProductLimits = new HashSet<ProductLimit>();
            TriggerProductSettings = new HashSet<TriggerProductSetting>();
            ProductCountrySettings = new HashSet<ProductCountrySetting>();
        }

        public int Id { get; set; }
        public long TranslationId { get; set; }
        public int? GameProviderId { get; set; }
        public int? PaymentSystemId { get; set; }
        public int Level { get; set; }
        public string NickName { get; set; }
        public int? ParentId { get; set; }
        public string ExternalId { get; set; }
        public int State { get; set; }
        public bool IsForDesktop { get; set; }
        public bool IsForMobile { get; set; }
        public string WebImageUrl { get; set; }
        public string MobileImageUrl { get; set; }
        public int? SubproviderId { get; set; }
        public bool HasDemo { get; set; }
        public int? CategoryId { get; set; }
        public string Jackpot { get; set; }
        public bool? FreeSpinSupport { get; set; }
        public string BackgroundImageUrl { get; set; }
        public decimal? RTP { get; set; }
        public System.DateTime CreationTime { get; set; }
        public System.DateTime LastUpdateTime { get; set; }
        public virtual GameProvider GameProvider { get; set; }
        public virtual Product Parent { get; set; }
        public virtual GameProvider Subprovider { get; set; }
        public virtual Translation Translation { get; set; }
        public virtual ICollection<AgentCommission> AgentCommissions { get; set; }
        public virtual ICollection<AgentProfit> AgentProfitProductGroups { get; set; }
        public virtual ICollection<AgentProfit> AgentProfitProducts { get; set; }
        public virtual ICollection<BetShopTicket> BetShopTickets { get; set; }
        public virtual ICollection<Bet> Bets { get; set; }
        public virtual ICollection<BonusProduct> BonusProducts { get; set; }
        public virtual ICollection<ClientClassification> ClientClassifications { get; set; }
        public virtual ICollection<ClientFavoriteProduct> ClientFavoriteProducts { get; set; }
        public virtual ICollection<ClientSession> ClientSessions { get; set; }
        public virtual ICollection<ComplimentaryPointRate> ComplimentaryPointRates { get; set; }
        public virtual ICollection<Document> Documents { get; set; }
        public virtual ICollection<Product> InverseParent { get; set; }
        public virtual ICollection<JackpotSetting> JackpotSettings { get; set; }
        public virtual ICollection<PartnerProductSetting> PartnerProductSettings { get; set; }
        public virtual ICollection<ProductLimit> ProductLimits { get; set; }
        public virtual ICollection<TriggerProductSetting> TriggerProductSettings { get; set; }
        public virtual ICollection<ProductCountrySetting> ProductCountrySettings { get; set; }
    }
}