// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace IqSoft.CP.DAL
{
    public partial class TicketMessageState
    {
        public long Id { get; set; }
        public int? ClientId { get; set; }
        public long MessageId { get; set; }
        public DateTime CreationTime { get; set; }
        public int? UserId { get; set; }

        public virtual Client Client { get; set; }
        public virtual TicketMessage Message { get; set; }
        public virtual User User { get; set; }
    }
}