// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace IqSoft.CP.DAL
{
    public partial class Transaction
    {
        public long Id { get; set; }
        public long DocumentId { get; set; }
        public long AccountId { get; set; }
        public decimal Amount { get; set; }
        public int OperationTypeId { get; set; }
        public int Type { get; set; }
        public DateTime CreationTime { get; set; }
        public long? Date { get; set; }

        public virtual Account Account { get; set; }
        public virtual Document Document { get; set; }
    }
}