// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace IqSoft.CP.DAL
{
    public partial class Translation
    {
        public Translation()
        {
            Actions = new HashSet<Action>();
            BannerBodyTranslations = new HashSet<Banner>();
            BannerHeadTranslations = new HashSet<Banner>();
            Bonus = new HashSet<Bonu>();
            ClientCategories = new HashSet<ClientCategory>();
            CommentTemplates = new HashSet<CommentTemplate>();
            Enumerations = new HashSet<Enumeration>();
            JobAreas = new HashSet<JobArea>();
            MessageTemplates = new HashSet<MessageTemplate>();
            OperationTypes = new HashSet<OperationType>();
            PartnerBankInfoes = new HashSet<PartnerBankInfo>();
            PaymentSystems = new HashSet<PaymentSystem>();
            ProductCategories = new HashSet<ProductCategory>();
            Products = new HashSet<Product>();
            PromotionContentTranslations = new HashSet<Promotion>();
            PromotionDescriptionTranslations = new HashSet<Promotion>();
            PromotionTitleTranslations = new HashSet<Promotion>();
            Regions = new HashSet<Region>();
            TranslationEntries = new HashSet<TranslationEntry>();
            TriggerSettings = new HashSet<TriggerSetting>();
            WebSiteSubMenuItems = new HashSet<WebSiteSubMenuItem>();
        }

        public long Id { get; set; }
        public int ObjectTypeId { get; set; }
        public long SessionId { get; set; }
        public DateTime CreationTime { get; set; }
        public DateTime LastUpdateTime { get; set; }

        public virtual ErrorType ErrorType { get; set; }
        public virtual SecurityQuestion SecurityQuestion { get; set; }
        public virtual ICollection<Action> Actions { get; set; }
        public virtual ICollection<Banner> BannerBodyTranslations { get; set; }
        public virtual ICollection<Banner> BannerHeadTranslations { get; set; }
        public virtual ICollection<Bonu> Bonus { get; set; }
        public virtual ICollection<ClientCategory> ClientCategories { get; set; }
        public virtual ICollection<CommentTemplate> CommentTemplates { get; set; }
        public virtual ICollection<Enumeration> Enumerations { get; set; }
        public virtual ICollection<JobArea> JobAreas { get; set; }
        public virtual ICollection<MessageTemplate> MessageTemplates { get; set; }
        public virtual ICollection<OperationType> OperationTypes { get; set; }
        public virtual ICollection<PartnerBankInfo> PartnerBankInfoes { get; set; }
        public virtual ICollection<PaymentSystem> PaymentSystems { get; set; }
        public virtual ICollection<ProductCategory> ProductCategories { get; set; }
        public virtual ICollection<Product> Products { get; set; }
        public virtual ICollection<Promotion> PromotionContentTranslations { get; set; }
        public virtual ICollection<Promotion> PromotionDescriptionTranslations { get; set; }
        public virtual ICollection<Promotion> PromotionTitleTranslations { get; set; }
        public virtual ICollection<Region> Regions { get; set; }
        public virtual ICollection<TranslationEntry> TranslationEntries { get; set; }
        public virtual ICollection<TriggerSetting> TriggerSettings { get; set; }
        public virtual ICollection<WebSiteSubMenuItem> WebSiteSubMenuItems { get; set; }
    }
}