// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace IqSoft.CP.DAL
{
    public partial class TriggerGroup
    {
        public TriggerGroup()
        {
            TriggerGroupSettings = new HashSet<TriggerGroupSetting>();
        }

        public int Id { get; set; }
        public string Name { get; set; }
        public int BonusId { get; set; }
        public int Type { get; set; }
        public int Priority { get; set; }

        public virtual Bonu Bonus { get; set; }
        public virtual ICollection<TriggerGroupSetting> TriggerGroupSettings { get; set; }
    }
}