// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace IqSoft.CP.DAL
{
    public partial class User
    {
        public User()
        {
            AgentCommissions = new HashSet<AgentCommission>();
            AgentProfitAgents = new HashSet<AgentProfit>();
            AgentProfitFromAgents = new HashSet<AgentProfit>();
            Announcements = new HashSet<Announcement>();
            BetShopReconings = new HashSet<BetShopReconing>();
            Bets = new HashSet<Bet>();
            CashDeskShifts = new HashSet<CashDeskShift>();
            CashDesks = new HashSet<CashDesk>();
            ClientIdentities = new HashSet<ClientIdentity>();
            ClientSettings = new HashSet<ClientSetting>();
            Clients = new HashSet<Client>();
            ObjectDataChangeHistories = new HashSet<ObjectDataChangeHistory>();
            PaymentRequests = new HashSet<PaymentRequest>();
            TicketMessageStates = new HashSet<TicketMessageState>();
            TicketMessages = new HashSet<TicketMessage>();
            Tickets = new HashSet<Ticket>();
            UserLogs = new HashSet<UserLog>();
            UserRoles = new HashSet<UserRole>();
            UserSessions = new HashSet<UserSession>();
            UserSettings = new HashSet<UserSetting>();
        }

        public int Id { get; set; }
        public int PartnerId { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public int Gender { get; set; }
        public string LanguageId { get; set; }
        public string UserName { get; set; }
        public string NickName { get; set; }
        public string PasswordHash { get; set; }
        public int Salt { get; set; }
        public int State { get; set; }
        public string CurrencyId { get; set; }
        public string Email { get; set; }
        public string MobileNumber { get; set; }
        public int Type { get; set; }
        public string AdminState { get; set; }
        public int? ParentId { get; set; }
        public string Path { get; set; }
        public string SecurityCode { get; set; }
        public string QRCode { get; set; }
        public bool IsTwoFactorEnabled { get; set; }
        public int? Level { get; set; }
        public DateTime CreationTime { get; set; }
        public DateTime LastUpdateTime { get; set; }
        public long SessionId { get; set; }
        public byte[] ImageData { get; set; }
        public DateTime? PasswordChangedDate { get; set; }
        public bool? LoginByNickName { get; set; }
        public string Phone { get; set; }

        public virtual Currency Currency { get; set; }
        public virtual Language Language { get; set; }
        public virtual Partner Partner { get; set; }
        public virtual UserSession Session { get; set; }
        public virtual ICollection<AgentCommission> AgentCommissions { get; set; }
        public virtual ICollection<AgentProfit> AgentProfitAgents { get; set; }
        public virtual ICollection<AgentProfit> AgentProfitFromAgents { get; set; }
        public virtual ICollection<Announcement> Announcements { get; set; }
        public virtual ICollection<BetShopReconing> BetShopReconings { get; set; }
        public virtual ICollection<Bet> Bets { get; set; }
        public virtual ICollection<CashDeskShift> CashDeskShifts { get; set; }
        public virtual ICollection<CashDesk> CashDesks { get; set; }
        public virtual ICollection<ClientIdentity> ClientIdentities { get; set; }
        public virtual ICollection<ClientSetting> ClientSettings { get; set; }
        public virtual ICollection<Client> Clients { get; set; }
        public virtual ICollection<ObjectDataChangeHistory> ObjectDataChangeHistories { get; set; }
        public virtual ICollection<PaymentRequest> PaymentRequests { get; set; }
        public virtual ICollection<TicketMessageState> TicketMessageStates { get; set; }
        public virtual ICollection<TicketMessage> TicketMessages { get; set; }
        public virtual ICollection<Ticket> Tickets { get; set; }
        public virtual ICollection<UserLog> UserLogs { get; set; }
        public virtual ICollection<UserRole> UserRoles { get; set; }
        public virtual ICollection<UserSession> UserSessions { get; set; }
        public virtual ICollection<UserSetting> UserSettings { get; set; }
    }
}