// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace IqSoft.CP.DAL
{
    public partial class UserLog
    {
        public long Id { get; set; }
        public int UserId { get; set; }
        public string Ip { get; set; }
        public string RequestMethod { get; set; }
        public string Page { get; set; }
        public string Info { get; set; }
        public DateTime CreationTime { get; set; }

        public virtual User User { get; set; }
    }
}