// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace IqSoft.CP.DAL
{
    public partial class WebSiteSubMenuItem
    {
        public int Id { get; set; }
        public int MenuItemId { get; set; }
        public string Icon { get; set; }
        public string Title { get; set; }
        public string Type { get; set; }
        public string Href { get; set; }
        public bool OpenInRouting { get; set; }
        public int Order { get; set; }
        public long? TranslationId { get; set; }
        public string StyleType { get; set; }

        public virtual WebSiteMenuItem MenuItem { get; set; }
        public virtual Translation Translation { get; set; }
    }
}