// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace IqSoft.CP.DAL
{
    public partial class WebSiteMenu
    {
        public WebSiteMenu()
        {
            WebSiteMenuItems = new HashSet<WebSiteMenuItem>();
        }

        public int Id { get; set; }
        public int PartnerId { get; set; }
        public string Type { get; set; }
        public string StyleType { get; set; }

        public virtual Partner Partner { get; set; }
        public virtual ICollection<WebSiteMenuItem> WebSiteMenuItems { get; set; }
    }
}