namespace IqSoft.CP.Common.Enums
{
    public enum OperationTypes
    {
        PaymentRequestBooking = 1,
        Bet = 3,
        Win = 4,
        Deposit = 5,
        ClientTransferToBetShop = 6,
        Rollback = 7,
        WageringBonus = 8,
        PayWinFromBetshop = 9,
        AffiliateBonus = 10,
        PayBetShopDebt = 11,
        PayPartnerPaymentSettingDebt = 12,
        AddMoneyToPartnerBank = 13,
        PayPartnerProductDebt = 14,
        BetRollback = 15,
        Jackpot = 16,
        WinRollback = 17,
        DebitCorrectionOnCashDesk = 18,
        CreditCorrectionOnCashDesk = 19,
        CancelWageringBonus = 20,
        DebitCorrectionOnClient = 21,
        CreditCorrectionOnClient = 22,
        TransferFromBetShopToClient = 23,
        RecalculationCredit = 24,
        RecalculationDebit = 25,
        CashOut = 26,
        CashBackBonus = 27,
        MultipleBonus = 28,
        CloseShiftCreditFromCashDesk = 29,
        CloseShiftDebitToCashDesk = 30,
        TransferFromCashDeskToUser = 31,
        Withdraw = 32,
        DepositRollback = 33,
        WithdrawRollback = 34,
        IncasationCreditFromCashDesk = 35,
        IncasationDebitToCashDesk = 36,
        BonusWin = 37,
        FreespinBonus = 38,
        DebitCorrectionOnUser = 39,
        CreditCorrectionOnUser = 40,
        CommissionForClient = 41,
        CommissionForUser = 42,
        ComplimentaryPointWin = 43,
        ComplimentaryPointSpend = 44,
        ChargeBack = 45,
        BonusExpiration = 46,
        DebitCorrectionOnAffiliate = 47,
        CreditCorrectionOnAffiliate = 48
    }
}