//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IqSoft.CP.DataWarehouse
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccountBalance
    {
        public long Id { get; set; }
        public long AccountId { get; set; }
        public long ObjectId { get; set; }
        public int ObjectTypeId { get; set; }
        public int TypeId { get; set; }
        public string CurrencyId { get; set; }
        public decimal Balance { get; set; }
        public System.DateTime Date { get; set; }
    }
}
