//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IqSoft.CP.DataWarehouse
{
    using System;
    using System.Collections.Generic;
    
    public partial class AffiliatePlatform
    {
        public int Id { get; set; }
        public int PartnerId { get; set; }
        public string Name { get; set; }
        public int Status { get; set; }
        public Nullable<System.DateTime> KickOffTime { get; set; }
        public Nullable<System.DateTime> LastExecutionTime { get; set; }
        public Nullable<int> StepInHours { get; set; }
        public Nullable<int> PeriodInHours { get; set; }
    }
}
