//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IqSoft.CP.DataWarehouse
{
    using System;
    using System.Collections.Generic;
    
    public partial class AffiliateReferral
    {
        public int Id { get; set; }
        public int AffiliatePlatformId { get; set; }
        public string AffiliateId { get; set; }
        public string RefId { get; set; }
        public int Type { get; set; }
        public System.DateTime CreationTime { get; set; }
        public int Status { get; set; }
        public Nullable<System.DateTime> LastProcessedBonusTime { get; set; }
    }
}
