//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IqSoft.CP.DataWarehouse
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bet
    {
        public long Id { get; set; }
        public long BetDocumentId { get; set; }
        public Nullable<long> WinDocumentId { get; set; }
        public Nullable<long> PayDocumentId { get; set; }
        public string CurrencyId { get; set; }
        public int ProductId { get; set; }
        public decimal BetAmount { get; set; }
        public decimal WinAmount { get; set; }
        public int State { get; set; }
        public int TypeId { get; set; }
        public Nullable<int> CashDeskId { get; set; }
        public Nullable<int> ClientId { get; set; }
        public Nullable<long> TicketNumber { get; set; }
        public Nullable<int> UserId { get; set; }
        public int DeviceTypeId { get; set; }
        public System.DateTime BetTime { get; set; }
        public Nullable<System.DateTime> CalculationTime { get; set; }
        public Nullable<System.DateTime> PayTime { get; set; }
        public long BetDate { get; set; }
        public Nullable<long> CalculationDate { get; set; }
        public Nullable<long> PayDate { get; set; }
        public Nullable<long> JackpotDocumentId { get; set; }
        public Nullable<long> BonusDocumentId { get; set; }
        public Nullable<int> BonusId { get; set; }
        public Nullable<int> SelectionsCount { get; set; }
        public Nullable<decimal> Coefficient { get; set; }
        public Nullable<System.DateTime> LastUpdateTime { get; set; }
        public Nullable<decimal> Rake { get; set; }
        public Nullable<decimal> BonusAmount { get; set; }
        public Nullable<long> AccountId { get; set; }
        public Nullable<decimal> BonusWinAmount { get; set; }
    }
}
