//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IqSoft.CP.DataWarehouse
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClientMatchHistory
    {
        public int Id { get; set; }
        public long DuplicateId { get; set; }
        public string MatchedData { get; set; }
        public System.DateTime CreationDate { get; set; }
        public System.DateTime LastUpdateDate { get; set; }
        public long MatchDate { get; set; }
    
        public virtual DuplicatedClient DuplicatedClient { get; set; }
    }
}
