//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IqSoft.CP.DataWarehouse
{
    using System;
    using System.Collections.Generic;
    
    public partial class Document
    {
        public long Id { get; set; }
        public string ExternalTransactionId { get; set; }
        public decimal Amount { get; set; }
        public string CurrencyId { get; set; }
        public int State { get; set; }
        public int OperationTypeId { get; set; }
        public Nullable<int> TypeId { get; set; }
        public Nullable<long> ParentId { get; set; }
        public Nullable<long> PaymentRequestId { get; set; }
        public string RoundId { get; set; }
        public string Info { get; set; }
        public Nullable<int> Creator { get; set; }
        public Nullable<int> CashDeskId { get; set; }
        public Nullable<int> PartnerPaymentSettingId { get; set; }
        public Nullable<int> PartnerProductId { get; set; }
        public Nullable<int> GameProviderId { get; set; }
        public Nullable<int> ClientId { get; set; }
        public Nullable<long> ExternalOperationId { get; set; }
        public Nullable<long> TicketNumber { get; set; }
        public string TicketInfo { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<int> DeviceTypeId { get; set; }
        public Nullable<decimal> PossibleWin { get; set; }
        public Nullable<long> SessionId { get; set; }
        public System.DateTime CreationTime { get; set; }
        public System.DateTime LastUpdateTime { get; set; }
        public Nullable<int> ProductId { get; set; }
        public Nullable<bool> HasNote { get; set; }
        public Nullable<long> Date { get; set; }
        public Nullable<int> PartnerId { get; set; }
        public Nullable<long> AccountId { get; set; }
    }
}
