//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IqSoft.CP.DataWarehouse
{
    using System;
    
    public partial class fnAffiliateClient
    {
        public string AffiliateManagerId { get; set; }
        public int ClientId { get; set; }
        public Nullable<decimal> TotalBetAmount { get; set; }
        public Nullable<decimal> TotalWinAmount { get; set; }
    }
}
