//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IqSoft.CP.DataWarehouse
{
    using System;
    
    public partial class fnAffiliateCorrection
    {
        public long Id { get; set; }
        public int PartnerId { get; set; }
        public int AffiliateId { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public decimal Amount { get; set; }
        public string CurrencyId { get; set; }
        public Nullable<int> Creator { get; set; }
        public System.DateTime CreationTime { get; set; }
        public System.DateTime LastUpdateTime { get; set; }
        public Nullable<bool> HasNote { get; set; }
        public Nullable<long> Date { get; set; }
        public string OperationTypeName { get; set; }
        public string CreatorFirstName { get; set; }
        public string CreatorLastName { get; set; }
        public Nullable<int> DocumentTypeId { get; set; }
        public Nullable<int> ClientId { get; set; }
        public string ClientFirstName { get; set; }
        public string ClientLastName { get; set; }
    }
}
