//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IqSoft.CP.DataWarehouse
{
    using System;
    
    public partial class fnClientBets
    {
        public Nullable<int> ClientId { get; set; }
        public Nullable<decimal> BetAmount { get; set; }
        public Nullable<decimal> BonusBetAmount { get; set; }
        public Nullable<int> TotalBetsCount { get; set; }
        public Nullable<int> SportBetsCount { get; set; }
        public Nullable<decimal> WinAmount { get; set; }
        public Nullable<decimal> BonusWinAmount { get; set; }
        public Nullable<int> WinCount { get; set; }
    }
}
