//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IqSoft.CP.DataWarehouse
{
    using System;
    
    public partial class fnDocument
    {
        public long Id { get; set; }
        public Nullable<int> ClientId { get; set; }
        public int PartnerId { get; set; }
        public decimal Amount { get; set; }
        public string CurrencyId { get; set; }
        public string ExternalTransactionId { get; set; }
        public int State { get; set; }
        public int OperationTypeId { get; set; }
        public Nullable<int> TypeId { get; set; }
        public Nullable<long> PaymentRequestId { get; set; }
        public Nullable<int> PaymentSystemId { get; set; }
        public string PaymentSystemName { get; set; }
        public string RoundId { get; set; }
        public Nullable<int> GameProviderId { get; set; }
        public string GameProviderName { get; set; }
        public Nullable<int> ProductId { get; set; }
        public string ProductName { get; set; }
        public System.DateTime CreationTime { get; set; }
        public System.DateTime LastUpdateTime { get; set; }
        public Nullable<long> Date { get; set; }
        public Nullable<long> AccountId { get; set; }
    }
}
