//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IqSoft.CP.DataWarehouse
{
    using System;
    
    public partial class fnDuplicateClient
    {
        public int DuplicatedClientId { get; set; }
        public string DuplicatedData { get; set; }
        public System.DateTime LastUpdateTime { get; set; }
    }
}
