//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IqSoft.CP.DataWarehouse
{
    using System;
    
    public partial class fnInternetGame
    {
        public int ProductId { get; set; }
        public string ProductName { get; set; }
        public Nullable<int> GameProviderId { get; set; }
        public Nullable<int> SubproviderId { get; set; }
        public string CurrencyId { get; set; }
        public Nullable<decimal> BetAmount { get; set; }
        public Nullable<decimal> WinAmount { get; set; }
        public Nullable<decimal> GGR { get; set; }
        public Nullable<int> BetCount { get; set; }
        public int PartnerId { get; set; }
    }
}
