//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IqSoft.CP.DataWarehouse
{
    using System;
    
    public partial class fnPartnerDeviceBets
    {
        public int PartnerId { get; set; }
        public string CurrencyId { get; set; }
        public int DeviceTypeId { get; set; }
        public Nullable<int> PlayersCount { get; set; }
        public Nullable<decimal> MaxBet { get; set; }
        public Nullable<decimal> MaxWin { get; set; }
        public Nullable<decimal> TotalBet { get; set; }
        public Nullable<decimal> TotalBonusBet { get; set; }
        public Nullable<decimal> TotalWin { get; set; }
        public Nullable<decimal> TotalBonusWin { get; set; }
        public Nullable<decimal> CashoutAmount { get; set; }
        public Nullable<int> Count { get; set; }
    }
}
