//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IqSoft.CP.DataWarehouse
{
    using System;
    
    public partial class fnProviderClientsCount
    {
        public int PartnerId { get; set; }
        public Nullable<int> GameProviderId { get; set; }
        public Nullable<int> SubProviderId { get; set; }
        public Nullable<int> PlayersCount { get; set; }
    }
}
