//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IqSoft.CP.DataWarehouse
{
    using System;
    using System.Collections.Generic;
    
    public partial class GameProvider
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public int Type { get; set; }
        public Nullable<int> SessionExpireTime { get; set; }
        public string GameLaunchUrl { get; set; }
    }
}
