//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IqSoft.CP.DataWarehouse
{
    using System;
    using System.Collections.Generic;
    
    public partial class Gtd_Client_Info
    {
        public int Id { get; set; }
        public long Date { get; set; }
        public int ClientId { get; set; }
        public decimal TotalDepositAmount { get; set; }
        public int TotalDepositCount { get; set; }
        public decimal TotalWithdrawalAmount { get; set; }
        public int TotalWithdrawalCount { get; set; }
        public decimal TotalBetAmount { get; set; }
        public int TotalBetCount { get; set; }
        public decimal SportBetAmount { get; set; }
        public int SportBetCount { get; set; }
        public decimal TotalWinAmount { get; set; }
        public int TotalWinCount { get; set; }
        public int SportWinCount { get; set; }
        public decimal GGR { get; set; }
        public decimal TotalDebitCorrectionAmount { get; set; }
        public int TotalDebitCorrectionCount { get; set; }
        public decimal TotalCreditCorrectionAmount { get; set; }
        public int TotalCreditCorrectionCount { get; set; }
        public decimal ComplementaryBalance { get; set; }
        public decimal TotalBonusAmount { get; set; }
        public decimal NGR { get; set; }
    }
}
