//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IqSoft.CP.DataWarehouse
{
    using System;
    using System.Collections.Generic;
    
    public partial class Gtd_Dashboard_Info
    {
        public int Id { get; set; }
        public long Date { get; set; }
        public int PartnerId { get; set; }
        public int VisitorsCount { get; set; }
        public int SignUpsCount { get; set; }
        public int TotalPlayersCount { get; set; }
        public int ReturnsCount { get; set; }
        public int DepositsCount { get; set; }
        public decimal BonusAmount { get; set; }
        public decimal CashoutAmount { get; set; }
        public decimal MaxBet { get; set; }
        public decimal MaxWin { get; set; }
        public decimal BetAmount { get; set; }
        public decimal DesktopBetAmount { get; set; }
        public decimal MobileBetAmount { get; set; }
        public decimal TabletBetAmount { get; set; }
        public decimal BetShopBetAmount { get; set; }
        public decimal TerminalBetAmount { get; set; }
        public decimal ApplicationBetAmount { get; set; }
        public decimal GGR { get; set; }
        public decimal DesktopGGR { get; set; }
        public decimal MobileGGR { get; set; }
        public decimal TabletGGR { get; set; }
        public decimal BetShopGGR { get; set; }
        public decimal TerminalGGR { get; set; }
        public decimal ApplicationGGR { get; set; }
        public decimal NGR { get; set; }
        public decimal DesktopNGR { get; set; }
        public decimal MobileNGR { get; set; }
        public decimal TabletNGR { get; set; }
        public decimal BetShopNGR { get; set; }
        public decimal TerminalNGR { get; set; }
        public decimal ApplicationNGR { get; set; }
        public int BetsCount { get; set; }
        public int DesktopBetsCount { get; set; }
        public int MobileBetsCount { get; set; }
        public int TabletBetsCount { get; set; }
        public int BetShopBetsCount { get; set; }
        public int TerminalBetsCount { get; set; }
        public int ApplicationBetsCount { get; set; }
        public int PlayersCount { get; set; }
        public int DesktopPlayersCount { get; set; }
        public int MobilePlayersCount { get; set; }
        public int TabletPlayersCount { get; set; }
        public int BetShopPlayersCount { get; set; }
        public int TerminalPlayersCount { get; set; }
        public int ApplicationPlayersCount { get; set; }
        public int FTDCount { get; set; }
    }
}
