//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IqSoft.CP.DataWarehouse
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public int Id { get; set; }
        public long TranslationId { get; set; }
        public Nullable<int> GameProviderId { get; set; }
        public Nullable<int> PaymentSystemId { get; set; }
        public int Level { get; set; }
        public string NickName { get; set; }
        public Nullable<int> ParentId { get; set; }
        public string ExternalId { get; set; }
        public int State { get; set; }
        public bool IsForDesktop { get; set; }
        public bool IsForMobile { get; set; }
        public string WebImageUrl { get; set; }
        public string MobileImageUrl { get; set; }
        public Nullable<int> SubproviderId { get; set; }
        public bool HasDemo { get; set; }
        public Nullable<int> CategoryId { get; set; }
        public string Jackpot { get; set; }
        public Nullable<bool> FreeSpinSupport { get; set; }
        public string BackgroundImageUrl { get; set; }
        public Nullable<decimal> RTP { get; set; }
        public System.DateTime CreationTime { get; set; }
        public System.DateTime LastUpdateTime { get; set; }
        public string Lines { get; set; }
        public string BetValues { get; set; }
        public string Path { get; set; }
    }
}
