using System.Collections.Generic;
namespace IqSoft.CP.Integration
{
    public class CommonHelpers
    {
        public readonly static Dictionary<string, string> LanguageISOCodes = new Dictionary<string, string>
        {
            { "en", "en_US" },
            { "ru", "ru_RU" },
            { "es", "es_ES" },
            { "br", "pt_BR" },
            { "fr", "fr_FR" },
            { "id", "id_ID" },
            { "fa", "fa_IR" },
            { "hy", "hy_AM" },
            { "kk", "kk_KZ" },
            { "tr", "tr_TR"},
            { "de", "de_DE"},
            { "tj", "tj_TJ" },
            { "tl", "tl_PH"},
            { "ua", "ua_UK" },
            { "uz", "uz_UZ" },
            { "vi", "vi_VN" },
            { "zu", "zu_ZA"},
            { "af", "af_AF"},
            { "bd", "bd_BE"},
            { "ar", "ar_AR"},
            { "be", "be_BL"},
            { "bg", "bg_BU"},
            { "bn", "bn_BY"},
            { "bs", "bs_BO"},
            { "cs", "cs_CZ"},
            { "da", "da_DK" },
            { "el", "el_GR" },
            { "et", "et_EE" },
            { "eu", "eu_BA" },
            { "fi", "fi_FI" },
            { "fy", "fy_WF" },
            { "hi", "hi_IN" },
            { "he", "he_IL" },
            { "hr", "hr_HR" },
            { "hu", "hu_HU" },
            { "it", "it_IT" },
            { "ja", "ja_JP" },
            { "ka", "ka_GE" },
            { "km", "km_CK" },
            { "ko", "ko_KR" },
            { "ku", "ku_KU" },
            { "lt", "lt_LT" },
            { "lv", "lv_LV" },
            { "mk", "mk_MK" },
            { "mn", "mn_MN" },
            { "ms", "ms_MY" },
            { "my", "my_BU" },
            { "ne", "ne_NE" },
            { "nn", "nn_NO" },
            { "pa", "pa_PU" },
            { "pl", "pl_PL" },
            { "pt", "pt_PT" },
            { "ro", "ro_RO" },
            { "sd", "sd_SD" },
            { "sk", "sk_SK" },
            { "sl", "sl_SL" },
            { "sm", "sm_SM" },
            { "so", "so_SO" },
            { "sq", "sq_AL" },
            { "sr", "sr_SE" },
            { "st", "st_SO" },
            { "su", "su_SU" },
            { "sv", "sv_SE" },
            { "sw", "sw_SW" },
            { "te", "te_TE" },
            { "th", "th_TH" }
        };

        public readonly static Dictionary<string, string> LanguageISO3Codes = new Dictionary<string, string>
        {
            { "en", "ENG" },
            { "ru", "RUS" },
            { "es", "SPA" },
            { "pl", "PLS" },
            { "tr", "TRK" },
            { "it", "ITA" },
            { "ka", "GEO" },
            { "sv", "SWE" },
            { "be", "BEL" },
            { "fr", "FRE" },
            { "uk", "UKR" },
            { "ar", "ARA" },
            { "id", "IND"},
            { "zh", "ZHO"}
        };

        public readonly static Dictionary<string, string> LanguageISO5646Codes = new Dictionary<string, string>
        {
             { "en", "en-Us" },
            { "th", "th"},
            { "zh", "zh-Hans"},
            { "vi", "vi" },
            { "ko", "ko"},
            { "ja", "ja"},
            { "id", "id-id"},
            { "ru", "ru" },
            { "es", "es" },
            { "fr", "fr" },
            { "fa", "fa" },
            { "hy", "hy_AM" },
            { "kk", "kk_KZ" },
            { "tr", "tr_TR"},
            { "de", "de_DE"},
            { "tj", "tj_TJ" },
            { "tl", "tl_PH"},
            { "ua", "ua_UK" },
            { "uz", "uz_UZ" },
            { "zu", "zu_ZA"},
            { "af", "af_AF"},
            { "bd", "bd_BE"},
            { "ar", "ar_AR"},
            { "be", "be_BL"},
            { "bg", "bg_BU"},
            { "bn", "bn_BY"},
            { "bs", "bs_BO"},
            { "cs", "cs_CZ"},
            { "da", "da_DK" },
            { "el", "el_GR" },
            { "et", "et_EE" },
            { "eu", "eu_BA" },
            { "fi", "fi_FI" },
            { "fy", "fy_WF" },
            { "hi", "hi_IN" },
            { "he", "he_IL" },
            { "hr", "hr_HR" },
            { "hu", "hu_HU" },
            { "it", "it_IT" },
            { "ka", "ka_GE" },
            { "km", "km_CK" },
            { "ku", "ku_KU" },
            { "lt", "lt_LT" },
            { "lv", "lv_LV" },
            { "mk", "mk_MK" },
            { "mn", "mn_MN" },
            { "ms", "ms_MY" },
            { "my", "my_BU" },
            { "ne", "ne_NE" },
            { "nn", "nn_NO" },
            { "pa", "pa_PU" },
            { "pl", "pl_PL" },
            { "pt", "pt_PT" },
            { "ro", "ro_RO" },
            { "sd", "sd_SD" },
            { "sk", "sk_SK" },
            { "sl", "sl_SL" },
            { "sm", "sm_SM" },
            { "so", "so_SO" },
            { "sq", "sq_AL" },
            { "sr", "sr_SE" },
            { "st", "st_SO" },
            { "su", "su_SU" },
            { "sv", "sv_SE" },
            { "sw", "sw_SW" },
            { "te", "te_TE" }
        };
    }
}